CMAKE_MINIMUM_REQUIRED(VERSION 2.8)
project(rauc_scripts)

install(FILES S60mdfenv DESTINATION etc/init.d PERMISSIONS
	OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)

if(RAUC_ENABLE MATCHES "yes")
	install(FILES trunk.cert.pem DESTINATION etc/rauc/ PERMISSIONS
		OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
	install(FILES switchroot_rauc.sh DESTINATION usr/bin PERMISSIONS
		OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
endif()

if(SWUPDATE_ENABLE MATCHES "yes")
	install(FILES trunk.cert.pem DESTINATION etc/swupdate/ PERMISSIONS
		OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
	install(FILES switchroot_swu.sh DESTINATION usr/bin PERMISSIONS
		OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
endif()
