INCLUDE_DIRECTORIES(../../include)
set(depend_share_lib rtsaudio rtstream asound)
FILE(GLOB SRC_LIST "*.c")
set(depend_static_lib librtstream.a soxr asound stdc++)

FOREACH(src ${SRC_LIST})
	get_filename_component(target ${src} NAME_WE)
	add_executable(${target} ${src})
	if (CONFIG_SHARE_SAMPLE MATCHES "y")
		target_link_libraries(${target} ${depend_share_lib})
	endif()
	if (NOT (CONFIG_SHARE_SAMPLE MATCHES "y"))
		target_link_libraries(${target} ${depend_static_lib})
	endif()
	install(TARGETS ${target} RUNTIME DESTINATION usr/bin)
ENDFOREACH(src)
