#!/bin/sh
#
# System setup at early boot
#

[ -r /etc/default/earlyset ] && . /etc/default/earlyset

initdevnod() {
	mknod /dev/usb_phy_mdio c 121 0
	mknod /dev/crypto c 124 0
	mknod /dev/ram0 b 1 0
}

sethostname() {
	ethaddr=$(fw_printenv ethaddr 2>/dev/null | awk '{print $1}')
	ethaddr=${ethaddr:17:8}
	hostname="IPCAM-"${ethaddr//:/}
	hostname $hostname
}

start() {
	if [ -d /sys/kernel/debug ]; then
		mount -t debugfs none /sys/kernel/debug
	fi

	mount -t ramfs ramfs /var
	mkdir -p /var/tmp /var/log /var/run /var/lock /var/spool /var/cache \
		/var/nm /var/conf

	initdevnod

	ifconfig lo 127.0.0.1

	sethostname

	# Set initial date/time
	date -s "2018-06-01 00:00:00" >/dev/null

	# disable watermark boost if MemTotal < 64000KB
	mm=$(cat /proc/meminfo | grep MemTotal | awk '{print $2}' 2>/dev/null)
	if [ $mm -lt 64000 ]; then
		echo 0 > /proc/sys/vm/watermark_boost_factor
	fi
}

stop() {
	:
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        stop
        start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
