LIBSOXR_CONF_OPTS += -DCMAKE_C_FLAGS="$(TARGET_CFLAGS) -fPIC" \
		-DBUILD_SHARED_LIBS=1 \
		-DBUILD_TESTS=0 \
		-DBUILD_EXAMPLES=0 \
		-DWITH_LSR_BINDINGS=0 \
		-DWITH_OPENMP=0 \
		-DWITH_DOUBLE_PRECISION=0 \
		-DWITH_SIMD=0 \
		-DWITH_AVFFT=0 \
		-DWITH_PFFFT=0
