#!/bin/sh

# udhcpc script edited by Tim Riker <Tim@Rikers.org>

[ -z "$1" ] && echo "Error: should be called from udhcpc" && exit 1

RESOLV_CONF="/etc/resolv.conf"
[ -e $RESOLV_CONF ] || touch $RESOLV_CONF
[ -n "$broadcast" ] && BROADCAST="broadcast $broadcast"
[ -n "$subnet" ] && NETMASK="netmask $subnet"

echo $1

ipc_saveip() {
        if [ "$interface" = "wlan0" ] || [ "$interface" = "eth0" ] ; then
                #echo interface=$interface > /tmp/static_ip.conf
                echo ip=$ip  > /tmp/static_ip.conf
                echo broadcast=$broadcast  >> /tmp/static_ip.conf
                echo subnet=$subnet  >> /tmp/static_ip.conf
                echo router=$router  >> /tmp/static_ip.conf
                echo dns=$dns >> /tmp/static_ip.conf
        fi
}

case "$1" in
        deconfig)
                /sbin/ifconfig $interface up
                /sbin/ifconfig $interface 0.0.0.0

                # drop info from this interface
                # resolv.conf may be a symlink to /tmp/, so take care
                TMPFILE=$(mktemp)
                grep -vE "# $interface\$" $RESOLV_CONF > $TMPFILE
                cat $TMPFILE > $RESOLV_CONF
                rm -f $TMPFILE

                if [ -x /usr/sbin/avahi-autoipd ]; then
                        /usr/sbin/avahi-autoipd -k $interface
                fi
                ;;

        leasefail|nak)
                if [ -x /usr/sbin/avahi-autoipd ]; then
                        /usr/sbin/avahi-autoipd -wD $interface --no-chroot
                fi
                ;;

        renew|bound)
                if [ -x /usr/sbin/avahi-autoipd ]; then
                        /usr/sbin/avahi-autoipd -k $interface
                fi
                /sbin/ifconfig $interface $ip $BROADCAST $NETMASK

                if [ -n "$router" ] ; then
                        echo "deleting routers"
                        while route del default gw 0.0.0.0 dev $interface 2> /dev/null; do
                                :
                        done

                        for i in $router ; do
                                route add default gw $i dev $interface
                        done
                fi

                # drop info from this interface
                # resolv.conf may be a symlink to /tmp/, so take care
                TMPFILE=$(mktemp)
                grep -vE "# $interface\$" $RESOLV_CONF > $TMPFILE
                cat $TMPFILE > $RESOLV_CONF
                rm -f $TMPFILE

                # prefer rfc3359 domain search list (option 119) if available
                if [ -n "$search" ]; then
                        search_list=$search
                elif [ -n "$domain" ]; then
                        search_list=$domain
                fi

                [ -n "$search_list" ] &&
                        echo "search $search_list # $interface" >> $RESOLV_CONF


                echo adding dns 8.8.8.8
                echo "nameserver 8.8.8.8 # $interface" >> $RESOLV_CONF
                echo adding dns 8.8.4.4
                echo "nameserver 8.8.4.4 # $interface" >> $RESOLV_CONF

                echo adding dns 2001:4860:4860::8888
                echo "nameserver 2001:4860:4860::8888 # $interface" >> $RESOLV_CONF
                echo adding dns 2001:4860:4860::8844
                echo "nameserver 2001:4860:4860::8844 # $interface" >> $RESOLV_CONF
                

                for i in $dns ; do
                        if [ $i != "0.0.0.0" ]; then
                                echo adding dns $i
                                echo "nameserver $i # $interface" >> $RESOLV_CONF
                        fi
                done
                sleep 2
                touch $RESOLV_CONF
                ipc_saveip
                ;;
esac

HOOK_DIR="$0.d"
for hook in "${HOOK_DIR}/"*; do
    [ -f "${hook}" -a -x "${hook}" ] || continue
    "${hook}" "${@}"
done

exit 0
