#!/bin/sh
# devtmpfs does not get automounted for initramfs

/bin/busybox mount -t devtmpfs devtmpfs /dev
/bin/busybox mount -t sysfs /sys /sys
/bin/busybox mount -t proc /proc /proc

#This may fail (E.G. booted with console=), and errors from exec will
# terminate the shell, so use a subshell for the test
if (exec 0</dev/console) 2>/dev/null; then
	exec 0</dev/console
	exec 1>/dev/console
	exec 2>/dev/console
fi
#exec /sbin/init "$@"

# Find and mount the new filesystem.
/bin/busybox mkdir -p /newroot
fs_mgr -a /etc/fstab.root

# Unmount everything else you've attached to rootfs.
/bin/busybox mount --move /sys /newroot/sys
/bin/busybox mount --move /proc /newroot/proc
/bin/busybox mount --move /dev /newroot/dev

# Now switch to the new filesystem, and run /sbin/init out of it.
# Don't forget the "exec" here, because you want the new init program
# to inherit PID 1.
exec /bin/busybox switch_root /newroot /sbin/init
