#!/usr/bin/env python3
# -*- coding:utf-8 -*-

import os
import sys
import re
import struct
import binascii
import burnheader
import part
from part import fde
from part import dmverity
from part import dmintegrity
import globalval
import mkuserfs
import mkcryptfs
import build_verity_img
from datetime import datetime
from shutil import copyfile

def print_highlight(string):
    print("\033[47;30m%s\033[0m" % (string))

def file_size(fname):
    return os.stat(fname).st_size


def file_checksum(fname):
    align = 0x100000000
    fd = open(fname, "rb")
    checksum = 0
    while True:
        c = fd.read(1)
        if not c:
            break
        checksum += struct.unpack("B", c)[0]
    return (align - checksum % align) & 0xFFFFFFFF


def config_val(line, base=10):
    return int(line.split("=")[1], base)

class configure:
    def init_header(self, ps):
        self.ps = ps
        self.append_gpt = 0

    def get_date_time(self, fname):
        year, month, day, hour, minute, second = (0, 0, 0, 0, 0, 0)
        self.time_map_dict = {
            "boot": "build/uboot-custom/include/generated/timestamp_autogenerated.h",
            "kernel": "build/linux-custom/include/generated/utsversion.h",
            "rootfs": "target/etc/version",
        }
        for key in self.time_map_dict:
            if key == fname:
                fn = self.directory + '/' + self.time_map_dict[fname]
                with open(fn) as f:
                    for line in f:
                        if fname == "rootfs":
                            pattern_s = r"(\d+)-(\d+)-(\d+) (\d+):(\d+):(\d+)"
                            pattern = re.compile(pattern_s)
                            match = pattern.match(line)
                            if match:
                                (year, month, day, hour, minute, second) = [t(s) for t,s in zip((int,int,int,int,int,int), re.search(pattern_s,line).groups())]
                                break
                        if fname == "kernel":
                            pattern_s = r"#define UTS_VERSION \"#(\d+) PREEMPT (\S+)\s+(\S+)\s+(\d+)\s+(\d+):(\d+):(\d+)\s+(\S+)\s+(\d+)\""
                            pattern = re.compile(pattern_s)
                            match = pattern.match(line)
                            if match:
                                (version, week_s, month_s, day, hour, minute, second, dst_s, year) = [t(s) for t,s in zip((int, str,str,int,int,int,int,str,int), re.search(pattern_s,line).groups())]
                                dt = datetime.strptime(month_s, '%b')
                                month = dt.month
                                break
                        if fname == "boot":
                            pattern_s = r"#define U_BOOT_DATE \"(\S+) (\d+) (\d+)\""
                            pattern = re.compile(pattern_s)
                            match = pattern.match(line)
                            if match:
                                (month_s, day, year) = [t(s) for t,s in zip((str,int,int), re.search(pattern_s,line).groups())]
                                dt = datetime.strptime(month_s, '%b')
                                month = dt.month
                            pattern_s = r"#define U_BOOT_TIME \"(\d+):(\d+):(\d+)\""
                            pattern = re.compile(pattern_s)
                            match = pattern.match(line)
                            if match:
                                (hour, minute, second) = [t(s) for t,s in zip((int,int,int), re.search(pattern_s,line).groups())]
                                break
        print("%s: %04d/%d/%02d %02d:%02d:%02d" % (fname, year, month, day, hour, minute, second))
        return "%04x%02x%02x%02x%02x%02x" % (year, month, day, hour, minute, second)

    def init_map(self):
        self.magic_dict = {
            "boot": "626f6f74",
            "kernel": "6c696e78",
            "rootfs": "726f6f74",
            "userdata": "6a667332",
            "mcu_fw": "6669726d",
            "hconf": "68636f6e",
            "ldc": "6c646300",
            "dtb": "64746200",
            "resvd": "72657376",
            "gpt_head": "67707468",
            "gpt_tail": "67707474",
            "rodata": "726f6474",
        }

        self.config_map = {}
        for item in self.ps.parts:
            burnaddr1 = item.name + "_addr"
            maxcnt1 = item.name + "_cnt"
            magic1 = "ffffffff"
            for key in self.magic_dict:
                if key == item.name:
                    magic1 = self.magic_dict[item.name]
            if item.name == "kernel_b" or item.name == "rootfs_b":
                name = item.name[0:-2]
                burnaddr2, maxcnt2, sector_size, flash_type = self.ps.get_burn_header(item.name)
                self.config_map[name][4] = burnaddr2
                self.config_map[name][5] = maxcnt2
            else:
                burnaddr, maxcnt, sector_size, flash_type = self.ps.get_burn_header(item.name)
                dt = self.get_date_time(item.name)
                self.config_map[item.name] = [magic1, burnaddr, maxcnt, dt, 0xffffffffffffffff, 0, sector_size, flash_type]
        self.config_map["---FEOF---"] = ["46454f46", 0xffffffffffffffff, 0, "00000000000000", 0xffffffffffffffff, 0, 0, " "]

    def __init__(self, ps, directory):
        self.kernel_cnt = 0
        self.directory = directory
        self.init_header(ps)
        self.init_map()

    def magic(self, key):
        return self.config_map[key][0]

    def burnaddr(self, key):
        return self.config_map[key][1]

    def max_cnt(self, key):
        return self.config_map[key][2]

    def burnaddr2(self, key):
        return self.config_map[key][4]

    def max_cnt2(self, key):
        return self.config_map[key][5]

    def date_time(self, key):
        return self.config_map[key][3]

    def max_size(self, key):
        return self.config_map[key][2] * self.config_map[key][6]

    def get_flash_type(self, key):
        return self.config_map[key][7]

    def is_exist(self, key):
        if key in self.config_map:
            return True
        return False

    def dump(self):
        print("filename\t magic\t\t burnaddr1(hex)\t\t maxcnt1(dec)\t burnaddr2(hex)\t\t maxcnt2(dec)\t flashtype")
        for key in self.config_map:
            align = "\t" if len(key) < 8 else ""
            item = self.config_map[key]
            print("%s\t %s\t %16x\t %4d\t\t %16x\t %4d\t\t %s" % (key + align,
                                           item[0], item[1], item[2], item[4], item[5], item[7]))

    def write_feof(self, fd):
        fd.write(binascii.a2b_hex(self.config_map["---FEOF---"][0]))

class head:
    def __init__(self, config, key, fname):
        self.flash_type_dict = {
            "nor": "00",
            "nand": "01",
            "emmc": "02"
        }
        fsize = file_size(fname)
        max_size = config.max_size(key)
        if max_size < fsize:
            print("ERROR: %s size 0x%x > 0x%x" % (fname, fsize, max_size))
            exit(1)
        self.magic = config.magic(key)
        self.date_time = config.date_time(key)
        flash_type = config.get_flash_type(key)
        self.flash_type = self.flash_type_dict[flash_type]
        self.partition_size = "%08x" % (max_size)
        self.addr = "%016x" % config.burnaddr(key)
        self.size = "%016x" % (fsize)
        self.content = self.magic + self.date_time + self.flash_type + self.partition_size + self.addr + self.size

    def dump(self):
        print(self.magic, self.flash_type)
        print(self.addr, self.size)

    def write(self, fd):
        fd.write(binascii.a2b_hex(self.content))


class tail:
    def __init__(self, fname):
        self.checksum = "%08x" % (file_checksum(fname))
        self.content = self.checksum

    def dump(self):
        print(self.checksum)

    def write(self, fd):
        fd.write(binascii.a2b_hex(self.content))


def file_align(fname, bytes=4):
    size = os.stat(fname).st_size
    print(fname, size)
    if size % bytes:
        falign = fname + ".align"
        with open(fname, "rb") as src:
            with open(falign, "wb") as dst:
                dst.write(src.read())
                dst.write(binascii.a2b_hex('ff' * (bytes - size % bytes)))
        return falign
    return fname


def file_append(fd, config, key, fname):
    fname = file_align(fname)
    print("append:", os.path.realpath(fname))
    if config.get_flash_type(key) == "emmc" and config.append_gpt == 0 and key != "boot":
        append_gpt(fd, config)

    h = head(config, key, fname)
    t = tail(fname)
    h.dump()
    print("[%s]" % (os.path.basename(fname)))
    t.dump()
    h.write(fd)
    fd.write(open(fname, 'rb').read())
    t.write(fd)


def file_raw_fill(fd, addr, key, fname):
    print("raw append:", key, os.path.realpath(fname))

    fd.seek(addr, 0)
    fd.write(open(fname, 'rb').read())

def file_raw_fullfill(fd, flash_size):
    pad_len = flash_size
    write_len = 1024 * 1024 * 10
    while pad_len > 0:
        if pad_len > 1024 * 1024 * 10:
            write_len = 1024 * 1024 * 10
        else:
            write_len = pad_len
        fd.write(binascii.a2b_hex('ff' * write_len))
        pad_len = pad_len - write_len


def file_raw_fill_gpt(fd, flash_size, directory):
    gpt_file = directory + "/gpt_head"
    addr = 0
    fd.seek(addr, 0)
    fd.write(open(gpt_file, 'rb').read())
    gpt_file = directory + "/gpt_tail"
    addr = flash_size - 33 * 512
    fd.seek(addr, 0)
    fd.write(open(gpt_file, 'rb').read())

def file_pairs(output_directory, scripts_directory, fini, user_fs, ps):
    pairs = []
    image_directory = output_directory + "/images"
    with open(fini) as fd:
        for line in fd:
            line = line.strip()
            if not line or line[:1] == "#":
                continue
            key, path = line.split("=")
            key = key.strip()
            path = path.strip()

            if path[0] != "/":
                path = os.path.join(image_directory, path)

            p = ps.get_part(key)

            # user partitions
            if p.get_group() == "user":
                # create userfs first
                mkuserfs.create(output_directory, scripts_directory, key, user_fs, p)

                cmode, smode = p.get_security_mode()

                # secure boot: dm-verity
                if isinstance(smode, dmverity):
                    tool_path = output_directory + "/host/sbin"
                    user_bin = path
                    user_bin_signed = user_bin + ".signed"
                    mount_point = p.get_mnt_point()
                    device = p.get_dmverity_data_dev()
                    if not device or not mount_point:
                        print("Error: can't get dmverity info...")
                        exit(1)
                    verity_key = smode.get_key_path()
                    path = user_bin_signed
                    build_verity_img.build_verity_img(tool_path, user_bin,
                        mount_point, device, verity_key, user_bin_signed)

                # secure boot: dm-integrity
                if isinstance(smode, dmintegrity) and part.dmintegrity().get_dmintegrity_type(board_config) == 1:
                    pid = os.getpid()
                    tool_path = output_directory + "/host/sbin"
                    user_bin = path
                    user_bin_signed = user_bin + ".signed"
                    path = user_bin_signed
                    cmd = "cp -a " + user_bin + " " + user_bin_signed
                    print("cmd", cmd)
                    os.system(cmd)
                    cmd = "sudo " + tool_path + "/integritysetup format -q " + user_bin_signed
                    print("cmd", cmd)
                    os.system(cmd)
                    cmd = "sudo " + tool_path + "/integritysetup open " + user_bin_signed + " dm-integrity-" + pid
                    print("cmd", cmd)
                    os.system(cmd)
                    cmd = "sudo " + tool_path + "/mkfs.ext4 -b 4096 -d " + output_directory + "/userdata /dev/mapper/dm-integrity-" + pid
                    print("cmd", cmd)
                    os.system(cmd)
                    cmd = "sudo " + tool_path + "/integritysetup close dm-integrity-" + pid
                    print("cmd", cmd)
                    os.system(cmd)

                # crypto boot: dm-crypt
                if isinstance(cmode, fde):
                    user_bin = path
                    user_bin_crypted = user_bin + ".crypted"
                    crypto_key = cmode.get_key_path()
                    path = user_bin_crypted
                    mkcryptfs.encrypt_fs(user_bin, user_bin_crypted, crypto_key, 4096)

            if not os.path.exists(path):
                is_raw = fini.find("raw.ini")
                if is_raw != -1:
                    print_highlight("ERROR: "+os.path.abspath(path)+" in raw.ini is not exist, so exit.")
                    return []
                print_highlight("WARNING: "+os.path.abspath(path)+" is not exist, so skip it.")
                continue
            pairs.append((key, path))

    return pairs

def append_gpt(fd, config):
    config.ps.creat_gpt(config.directory)
    config.ps.create_gpt_partition(config.directory)
    gpt_file = config.directory + "/images/gpt_head"
    fsize = file_size(gpt_file)
    max_size = fsize
    burnaddr = 0
    magic = config.magic_dict["gpt_head"]
    date_time = "00000000000000"
    flash_type = "02"
    partition_size = "%08x" % (max_size)
    addr = "%016x" % (burnaddr)
    size = "%016x" % (fsize)
    content = magic + date_time + flash_type + partition_size + addr + size
    fd.write(binascii.a2b_hex(content))
    fd.write(open(gpt_file, 'rb').read())
    checksum = "%08x" % (file_checksum(gpt_file))
    fd.write(binascii.a2b_hex(checksum))
    gpt_file = config.directory + "/images/gpt_tail"
    fsize = file_size(gpt_file)
    max_size = fsize
    burnaddr = config.ps.flash_size - 33 * 512
    magic = config.magic_dict["gpt_tail"]
    partition_size = "%08x" % (max_size)
    addr = "%016x" % (burnaddr)
    size = "%016x" % (fsize)
    content = magic + date_time + flash_type + partition_size + addr + size
    fd.write(binascii.a2b_hex(content))
    fd.write(open(gpt_file, 'rb').read())
    checksum = "%08x" % (file_checksum(gpt_file))
    fd.write(binascii.a2b_hex(checksum))
    config.append_gpt = 1

def create_dfu_file(output_directory, image_directory):
    customer_pid = []
    customer_vid = []
    host_dfu = output_directory + "/host/bin/dfu-suffix"
    source_bin = image_directory + "/linux.bin"
    vid_pid_ini = output_directory + "/customer.ini"

    if os.access(host_dfu, os.X_OK) and os.access(vid_pid_ini, os.R_OK):
        for vid in customer_vid:
            for pid in customer_pid:
                target_bin = image_directory + "/linux_" + vid + "_" + pid + ".bin"
                copyfile(source_bin, target_bin)
                cmd = "%s -a %s -v %s -p %s" % (host_dfu, target_bin, vid, pid)
                print(cmd)
                os.system(cmd)

if __name__ == "__main__":
    scripts_directory,scripts_name = os.path.split(sys.argv[0])
    output_directory = os.path.normpath(sys.argv[1])
    user_fs = os.path.normpath(sys.argv[2])
    board_config = os.path.normpath(sys.argv[3])
    image_directory = output_directory + "/images"
    build_directory = output_directory + "/build"
    uboot_directory = build_directory + "/uboot-custom"
    linux_directory = build_directory + "/linux-custom"
    merge_ini = output_directory + "/merge.ini"
    raw_ini = output_directory + "/raw.ini"
    target_bin = image_directory + "/linux.bin"
    header = image_directory + "/header"
    raw_bin = image_directory + "/raw.bin"

    print("board_config", board_config)
    gl = globalval.globalval(board_config)
    ic_type = gl.get_ic_type()
    default_config = gl.get_defconfig(linux_directory)

    if ic_type == 0 or default_config == "":
        print("Error, partition file cannot be found")

    print("target_bin %s." % (target_bin))
    print("raw.bin %s." % (raw_bin))
    print("merge.ini %s." % (merge_ini))
    print("raw.ini %s." % (raw_ini))

    ps = part.Parts(default_config, board_config)

    config = configure(ps, output_directory)
    config.dump()
    images_ini = file_pairs(output_directory, scripts_directory, merge_ini, user_fs, ps)

    fd = open(target_bin, "wb")
    burnheader.Header_info(output_directory, scripts_directory, user_fs, images_ini, config).write_header(fd)
    for key, fname in images_ini:
        if config.is_exist(key) == True:
            file_append(fd, config, key, fname)
        else:
            print_highlight("WARNING: "+key+" in merge.ini is not exist in partition.ini, so skip it.")
    config.write_feof(fd)
    fd.close()
    create_dfu_file(output_directory, image_directory)

    raw_ini = file_pairs(output_directory, scripts_directory, raw_ini, user_fs, ps)
    if raw_ini != []:
        find_uboot = False
        for key, fname in raw_ini:
            if key == "boot":
                find_uboot = True
        if find_uboot == True:
            burnaddr, maxcnt, sector_size, flash_type = ps.get_burn_header("boot")
            raw_bin = image_directory + "/raw_" + flash_type + ".bin"
            rawfd = open(raw_bin, "wb")

            flash_size = ps.flash_size
            file_raw_fullfill(rawfd, flash_size)
            if flash_type == "emmc":
                file_raw_fill_gpt(rawfd, flash_size, image_directory)

            for key, fname in raw_ini:
                for p in config.ps.parts:
                    if key == p.name:
                        burnaddr, maxcnt, sector_size, flash_type = config.ps.get_burn_header(key)
                        if flash_type == "emmc" and key != "boot":
                            file_raw_fill(rawfd, burnaddr, key, fname)
                        if flash_type != "emmc":
                            file_raw_fill(rawfd, burnaddr, key, fname)
            rawfd.close()
