/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (c) 2025 Realtek Semiconductor Corp. All rights reserved.
 *
 * THIS SOFTWARE IS CONFIDENTIAL AND PROPRIETARY TO REALTEK SEMICONDUCTOR
 * CORP. DISCLOSURE, REPRODUCTION, REDISTRIBUTION, IN WHOLE OR IN PART, OF
 * THIS WORK AND ITS DERIVATIVES WITHOUT EXPRESS PERMISSION IS PROHIBITED.
 *
 * REALTEK SEMICONDUCTOR CORP. RESERVES THE RIGHT TO UPDATE, MODIFY, OR
 * DISCONTINUE THIS SOFTWARE AT ANY TIME WITHOUT NOTICE. THIS SOFTWARE IS
 * PROVIDED BY THE REGENTS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE REGENTS AND CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

#ifndef _RTS_CAMERA_SOC_REGS_H
#define _RTS_CAMERA_SOC_REGS_H

/* register address */

#define RTS_REG_ISP_STREAM_EN_BASE			0x00000000
#define RTS_REG_ISP_STREAM_RST_BASE			0x00000030
#define RTS_REG_YUV_FRAME_BUFFER_STATUS_BASE		0x00000080
#define RTS_REG_YUV_FRAME_Y_START_ADDRESS_BASE		0x000000C0
#define RTS_REG_YUV_FRAME_UV_START_ADDRESS_BASE		0x000000D0
#define RTS_REG_YUV_FRAME_START_ADDRESS_INTERVAL	32
#define RTS_REG_YUV_FRAME_BUFFER_COUNT			0x00000180
#define RTS_REG_YUV_INTERLEAVE_SELECT			0x00000074
#define RTS_REG_ISP_NV12_SELECT				0x00000070

#define RTS_REG_YUV_AXI_BUF_CONFIG_BASE			0x000001A0
#define RTS_REG_YUV_AXI_Y_BUF_CONFIG_S0			\
				(RTS_REG_YUV_AXI_BUF_CONFIG_BASE + 4*0)
#define RTS_REG_YUV_AXI_UV_BUF_CONFIG_S0		\
				(RTS_REG_YUV_AXI_BUF_CONFIG_BASE + 4*1)
#define RTS_REG_YUV_AXI_Y_BUF_CONFIG_S1			\
				(RTS_REG_YUV_AXI_BUF_CONFIG_BASE + 4*2)
#define RTS_REG_YUV_AXI_UV_BUF_CONFIG_S1		\
				(RTS_REG_YUV_AXI_BUF_CONFIG_BASE + 4*3)
#define RTS_REG_YUV_AXI_Y_BUF_CONFIG_S2			\
				(RTS_REG_YUV_AXI_BUF_CONFIG_BASE + 4*4)
#define RTS_REG_YUV_AXI_UV_BUF_CONFIG_S2		\
				(RTS_REG_YUV_AXI_BUF_CONFIG_BASE + 4*5)
#define RTS_REG_YUV_AXI_Y_BUF_CONFIG_S3			\
				(RTS_REG_YUV_AXI_BUF_CONFIG_BASE + 4*6)
#define RTS_REG_YUV_AXI_UV_BUF_CONFIG_S3		\
				(RTS_REG_YUV_AXI_BUF_CONFIG_BASE + 4*7)
#define RTS_REG_YUV_FRAME_LEN_Y_BASE			0x000002A0
#define RTS_REG_YUV_FRAME_LEN_UV_BASE			0x000002A4
#define RTS_REG_YUV_FRAME_LEN_INTERVAL			8
#define RTS_REG_YUV_Y_CUR_FRAME_INDEX_OFFSET_BASE	0x000001D0
#define RTS_REG_YUV_CUR_FRAME_INDEX_OFFSET_INTERVAL	8

#define RTS_REG_RINGBUF_MODE				0x000002E0
#define RTS_REG_RINGBUF_ROWEND_DELAY			0x000002E4
#define RTS_REG_RINGBUF_ADDRY				0x000002E8
#define	RTS_REG_RINGBUF_ADDRUV				0x000002EC
#define RTS_REG_RINGBUF_LENY				0x000002F0
#define RTS_REG_RINGBUF_LENUV				0x000002F4

#define RTS_REG_INT_EN_ISP_TO_HOST			0x00000250
#define RTS_REG_INT_FLAG_ISP_HOST			0x00000254

#define RTS_REG_INT_EN_RGB_YONLY_TO_HOST		0x00000260
#define RTS_REG_INT_FLAG_RGB_YONLY_HOST			0x00000264
#define RTS_REG_ISP_RGB_YONLY_STREAM_EN			0x00000010
#define RTS_REG_ISP_RGB_YONLY_STREAM_RST		0x00000040
#define RTS_REG_RGB_YONLY_FRAME_BUFFER_STATUS		0x00000090
#define RTS_REG_RGB_R_FRAME_START_ADDRESS_BASE		0x00000140
#define RTS_REG_RGB_G_FRAME_START_ADDRESS_BASE		0x00000150
#define RTS_REG_RGB_B_FRAME_START_ADDRESS_BASE		0x00000160
#define RTS_REG_RGB_YONLY_FRAME_BUFFER_COUNT		0x00000188
#define RTS_REG_RGB_R_AXI_BUF_CONFIG			0x000001C0
#define RTS_REG_RGB_G_AXI_BUF_CONFIG			0x000001C4
#define RTS_REG_RGB_B_AXI_BUF_CONFIG			0x000001C8
#define RTS_REG_RGB_AXI_BUF_CONFIG_INTERVAL		4
#define RTS_REG_RGB_FRAME_LEN_R				0x000002C0
#define RTS_REG_RGB_FRAME_LEN_G				0x000002C4
#define RTS_REG_RGB_FRAME_LEN_B				0x000002C8
#define RTS_REG_RGB_R_CUR_FRAME_INDEX_OFFSET		0x000001F4

#endif
