/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (c) 2025 Realtek Semiconductor Corp. All rights reserved.
 *
 * THIS SOFTWARE IS CONFIDENTIAL AND PROPRIETARY TO REALTEK SEMICONDUCTOR
 * CORP. DISCLOSURE, REPRODUCTION, REDISTRIBUTION, IN WHOLE OR IN PART, OF
 * THIS WORK AND ITS DERIVATIVES WITHOUT EXPRESS PERMISSION IS PROHIBITED.
 *
 * REALTEK SEMICONDUCTOR CORP. RESERVES THE RIGHT TO UPDATE, MODIFY, OR
 * DISCONTINUE THIS SOFTWARE AT ANY TIME WITHOUT NOTICE. THIS SOFTWARE IS
 * PROVIDED BY THE REGENTS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE REGENTS AND CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

#ifndef _RTS_CAMERA_ISP_REGS_H
#define _RTS_CAMERA_ISP_REGS_H

#define SYS_REG_BASE 0x0000
#define SYS_CONTROL0 (SYS_REG_BASE + 0x0000)
#define SYS_INT_EN0 (SYS_REG_BASE + 0x0010)
#define SYS_INT_FLAG0 (SYS_REG_BASE + 0x0014)
#define SYS_INT_EN1 (SYS_REG_BASE + 0x0018)
#define SYS_INT_FLAG1 (SYS_REG_BASE + 0x001C)
#define SYS_DATA_DELAY (SYS_REG_BASE + 0x0040)
#define SYS_STATIS_CTRL (SYS_REG_BASE + 0x006C)

#define AWB_REG_BASE 0x7C00
#define AWB_FINE_WP_NUM (AWB_REG_BASE + 0x0080)
#define AWB_FINE_SUM_R (AWB_REG_BASE + 0x0084)
#define AWB_FINE_SUM_G (AWB_REG_BASE + 0x0088)
#define AWB_FINE_SUM_B (AWB_REG_BASE + 0x008C)
#define AWB_WP_NUM (AWB_REG_BASE + 0x00C0)

#define FLICK_REG_BASE 0x8800
#define FLICK_FFT_RESUT_SUM2_127 (FLICK_REG_BASE + 0x0010)
#define FLICK_FFT_RESUT_SUM2_9 (FLICK_REG_BASE + 0x0014)

#define STATIS_REG_BASE 0x8400
#define STATIS_CTRL (STATIS_REG_BASE + 0x0000)
#define STATIS_DDR_ADDR (STATIS_REG_BASE + 0x000C)
#define STATIS_DDR_LEN (STATIS_REG_BASE + 0x0010)
#define STATIS_BUF_SIZE (STATIS_REG_BASE + 0x0014)
#define STATIS_FRAME_STATE (STATIS_REG_BASE + 0x0038)

#define TNR_REG_BASE 0x2400
#define TNR_CTRL (TNR_REG_BASE + 0x0000)
#define TNR_STREAM_BUF_CFG (TNR_REG_BASE + 0x03D0)

/* SYS_INT_EN0 */
#define SENSOR0_FRAME_START_INT BIT(0)
#define SENSOR0_FRAME_END_INT BIT(1)
#define SENSOR1_FRAME_START_INT BIT(2)
#define SENSOR1_FRAME_END_INT BIT(3)
#define SENSOR0_DATA_START_INT BIT(8)
#define SENSOR0_DATA_END_INT BIT(9)
#define SENSOR1_DATA_START_INT BIT(10)
#define SENSOR1_DATA_END_INT BIT(11)
#define CROP0_DATA_START_INT BIT(16)
#define CROP0_DATA_END_INT BIT(17)
#define CROP1_DATA_START_INT BIT(18)
#define CROP1_DATA_END_INT BIT(19)
#define ISP_OUT_DATA_START_INT BIT(24)
#define ISP_OUT_DATA_END_INT BIT(25)
#define ISP_OUT_LINE_CNT_INT BIT(26)

/* SYS_INI_EN1 */
#define AE0_STATIS_INT BIT(0)
#define AE1_STATIS_INT BIT(1)
#define AE_STATIS_INT BIT(4)
#define RAW_STATIS_INT BIT(5)
#define FLICK_STATIS_INT BIT(6)
#define AWB_STATIS_INT BIT(7)
#define AF0_STATIS_INT BIT(8)
#define Y_STATIS_INT BIT(9)
#define AF1_STATIS_INT BIT(10)
#define STATIS_DONE_INT BIT(31)

#define STATIS_ALL_INT                                                         \
	(RAW_STATIS_INT | AF0_STATIS_INT | AF1_STATIS_INT | AWB_STATIS_INT |   \
	 AE_STATIS_INT | AE0_STATIS_INT | AE1_STATIS_INT | Y_STATIS_INT)
/* STATIS_CTRL */
#define STATIS_STREAM_EN 0x1

#endif /* _RTS_CAMERA_ISP_REGS_H */
