/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (c) 2025 Realtek Semiconductor Corp. All rights reserved.
 *
 * THIS SOFTWARE IS CONFIDENTIAL AND PROPRIETARY TO REALTEK SEMICONDUCTOR
 * CORP. DISCLOSURE, REPRODUCTION, REDISTRIBUTION, IN WHOLE OR IN PART, OF
 * THIS WORK AND ITS DERIVATIVES WITHOUT EXPRESS PERMISSION IS PROHIBITED.
 *
 * REALTEK SEMICONDUCTOR CORP. RESERVES THE RIGHT TO UPDATE, MODIFY, OR
 * DISCONTINUE THIS SOFTWARE AT ANY TIME WITHOUT NOTICE. THIS SOFTWARE IS
 * PROVIDED BY THE REGENTS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE REGENTS AND CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

#ifndef _U_RTS_CAMERA_ZOOM_REG_H
#define _U_RTS_CAMERA_ZOOM_REG_H

#define RTS_ZOOM_REG_SYS_CONTROL0		0
#define RTS_ZOOM_REG_SYS_CONTROL1		0x0004
#define RTS_ZOOM_REG_SYS_DATA_DELAY		0x0040
#define RTS_ZOOM_REG_SYS_IMAGE_SEL0		0x0048
#define RTS_ZOOM_REG_SYS_IMAGE_AI_CHAN_SEL	0x0078


#define RTS_ZOOM_REG_MCROP_STARTX		0x4c00
#define RTS_ZOOM_REG_MCROP_STARTY		0x4C04
#define RTS_ZOOM_REG_MCROP_FRAME_WIDTH		0x4c08
#define RTS_ZOOM_REG_MCROP_FRAME_HEIGHT		0x4c0c
#define RTS_ZOOM_REG_MCROP_LOAD			0x4c10


#define RTS_ZOOM_REG_BASE			0x10000
#define RTS_ZOOM_REG_CH0_CTRL			(RTS_ZOOM_REG_BASE + 0x0000)
#define RTS_ZOOM_REG_CH0_CROP_START		(RTS_ZOOM_REG_BASE + 0x0004)
#define RTS_ZOOM_REG_CH0_OUTPUT_SIZE		(RTS_ZOOM_REG_BASE + 0x0008)
#define RTS_ZOOM_REG_CH0_COEF0			(RTS_ZOOM_REG_BASE + 0x0010)
#define RTS_ZOOM_REG_CH0_COEF1			(RTS_ZOOM_REG_BASE + 0x0014)
#define RTS_ZOOM_REG_CH0_COEF2			(RTS_ZOOM_REG_BASE + 0x0018)
#define RTS_ZOOM_REG_CH0_COEF3			(RTS_ZOOM_REG_BASE + 0x001C)
#define RTS_ZOOM_REG_CH0_COEF4			(RTS_ZOOM_REG_BASE + 0x0020)
#define RTS_ZOOM_REG_CH0_STEP_V			(RTS_ZOOM_REG_BASE + 0x0048)
#define RTS_ZOOM_REG_CH0_STEP_H			(RTS_ZOOM_REG_BASE + 0x004C)
#define RTS_ZOOM_REG_CH0_REG_LOAD		(RTS_ZOOM_REG_BASE + 0x0024)
#define RTS_ZOOM_REG_CH_REG_OFFSET		0x80

#endif
