/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (c) 2025 Realtek Semiconductor Corp. All rights reserved.
 *
 * THIS SOFTWARE IS CONFIDENTIAL AND PROPRIETARY TO REALTEK SEMICONDUCTOR
 * CORP. DISCLOSURE, REPRODUCTION, REDISTRIBUTION, IN WHOLE OR IN PART, OF
 * THIS WORK AND ITS DERIVATIVES WITHOUT EXPRESS PERMISSION IS PROHIBITED.
 *
 * REALTEK SEMICONDUCTOR CORP. RESERVES THE RIGHT TO UPDATE, MODIFY, OR
 * DISCONTINUE THIS SOFTWARE AT ANY TIME WITHOUT NOTICE. THIS SOFTWARE IS
 * PROVIDED BY THE REGENTS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE REGENTS AND CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

#ifndef _RTS_CAMERA_CONFIG_H
#define _RTS_CAMERA_CONFIG_H

#define RTSCAM_MAX_STM_COUNT		5
#define RTSCAM_MAX_FPS_COUNT		32
#define RTSCAM_FPS_UNIT			10000000

#define RTSCAM_YUV_MAX_STRM_NUM		4
#define RTSCAM_MAX_STREAM_NUM		(RTSCAM_YUV_MAX_STRM_NUM + 1)
#define RTSCAM_RGB_YONLY_STRM_IDX	(RTSCAM_MAX_STREAM_NUM - 1)

/* format type */
#define RTSCAM_FORMAT_TYPE_YUV420_SEMIPLANAR		(1 << 0)
#define RTSCAM_FORMAT_TYPE_YUV422_SEMIPLANAR		(1 << 1)
#define RTSCAM_FORMAT_TYPE_RGB				(1 << 2)
#define RTSCAM_FORMAT_TYPE_Y_ONLY			(1 << 3)
#define RTSCAM_FORMAT_TYPE_YUYV				(1 << 4)
#define RTSCAM_FORMAT_TYPE_YVYU				(1 << 5)
#define RTSCAM_FORMAT_TYPE_128BIT_3PIXEL		(1 << 6)

/* 128 bits for every 3 pixels, MSB 20 bits unused */
#define V4L2_PIX_FMT_128BIT_3PIXEL	v4l2_fourcc('R', '1', '2', '8')

#endif
