/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (c) 2025 Realtek Semiconductor Corp. All rights reserved.
 *
 * THIS SOFTWARE IS CONFIDENTIAL AND PROPRIETARY TO REALTEK SEMICONDUCTOR
 * CORP. DISCLOSURE, REPRODUCTION, REDISTRIBUTION, IN WHOLE OR IN PART, OF
 * THIS WORK AND ITS DERIVATIVES WITHOUT EXPRESS PERMISSION IS PROHIBITED.
 *
 * REALTEK SEMICONDUCTOR CORP. RESERVES THE RIGHT TO UPDATE, MODIFY, OR
 * DISCONTINUE THIS SOFTWARE AT ANY TIME WITHOUT NOTICE. THIS SOFTWARE IS
 * PROVIDED BY THE REGENTS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE REGENTS AND CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

#ifndef _RTS_CAMERA_ZOOM_REGS_H
#define _RTS_CAMERA_ZOOM_REGS_H

#define ZOOM_SYS_REG_BASE 0x0
#define ZOOM_SYS_CONTROL (ZOOM_SYS_REG_BASE + 0x0000)
#define ZOOM_SYS_SPEED_CTRL (ZOOM_SYS_REG_BASE + 0x0004)
#define ZOOM_SYS_LAST_BREAK (ZOOM_SYS_REG_BASE + 0x0008)
#define ZOOM_SYS_DATA_ENABLE (ZOOM_SYS_REG_BASE + 0x000C)
#define ZOOM_SYS_DATA_DELAY (ZOOM_SYS_REG_BASE + 0x0010)
#define ZOOM_SYS_IMAGE_MODE_SEL (ZOOM_SYS_REG_BASE + 0x0018)
#define ZOOM_SYS_IMAGE_AI_CHAN_SEL (ZOOM_SYS_REG_BASE + 0x0020)
#define ZOOM_SYS_YUV_TRAN_CTRL (ZOOM_SYS_REG_BASE + 0x0028)

#define YUV422TORGB_REG_BASE 0x400
#define YUV2RGB0 (YUV422TORGB_REG_BASE + 0x0000)
#define YUV2RGB1 (YUV422TORGB_REG_BASE + 0x0004)
#define YUV2RGB2 (YUV422TORGB_REG_BASE + 0x0008)
#define YUV2RGB3 (YUV422TORGB_REG_BASE + 0x000C)
#define YUV2RGB4 (YUV422TORGB_REG_BASE + 0x0010)
#define YUV2RGB_YOFFSET (YUV422TORGB_REG_BASE + 0x0014)

#define ZOOM_REG_BASE 0xC00
#define ZOOM_CH0_CTRL (ZOOM_REG_BASE + 0x0000)
#define ZOOM_CH0_CROP_START (ZOOM_REG_BASE + 0x0004)
#define ZOOM_CH0_OUTPUT_SIZE (ZOOM_REG_BASE + 0x0008)
#define ZOOM_CH0_COEF0 (ZOOM_REG_BASE + 0x0010)
#define ZOOM_CH0_COEF1 (ZOOM_REG_BASE + 0x0014)
#define ZOOM_CH0_COEF2 (ZOOM_REG_BASE + 0x0018)
#define ZOOM_CH0_COEF3 (ZOOM_REG_BASE + 0x001C)
#define ZOOM_CH0_COEF4 (ZOOM_REG_BASE + 0x0020)
#define ZOOM_CH0_STEP_V (ZOOM_REG_BASE + 0x0048)
#define ZOOM_CH0_STEP_H (ZOOM_REG_BASE + 0x004C)
#define ZOOM_CH0_REG_LOAD (ZOOM_REG_BASE + 0x0024)
#define ZOOM_CH_REG_OFFSET 0x80

#define IVE_REG_BASE 0x11000
#define IVE_ENABLE (IVE_REG_BASE + 0x0000)
#define IVE_NORM_MEAN (IVE_REG_BASE + 0x0004)
#define IVE_NORM_SCALE (IVE_REG_BASE + 0x0008)
#define IVE_QUANT_LEN (IVE_REG_BASE + 0x000C)
#define IVE_ASYM_INV_SCALE (IVE_REG_BASE + 0x0010)
#define IVE_ASYM_ZERO_POINT (IVE_REG_BASE + 0x0014)

/* ZOOM_SYS_YUV_TRAN_CTRL */
#define LIMIT_MASK 0x11

/* ZOOM_CH0_CTRL */
#define ENABLE_ZOOM 0x1
#define DISABLE_ZOOM 0x2
/* ZOOM_CH0_REG_LOAD */
#define LOAD_ZOOM_PARAM 0x1

#endif /* _RTS_CAMERA_ZOOM_REGS_H */

