/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (c) 2025 Realtek Semiconductor Corp. All rights reserved.
 *
 * THIS SOFTWARE IS CONFIDENTIAL AND PROPRIETARY TO REALTEK SEMICONDUCTOR
 * CORP. DISCLOSURE, REPRODUCTION, REDISTRIBUTION, IN WHOLE OR IN PART, OF
 * THIS WORK AND ITS DERIVATIVES WITHOUT EXPRESS PERMISSION IS PROHIBITED.
 *
 * REALTEK SEMICONDUCTOR CORP. RESERVES THE RIGHT TO UPDATE, MODIFY, OR
 * DISCONTINUE THIS SOFTWARE AT ANY TIME WITHOUT NOTICE. THIS SOFTWARE IS
 * PROVIDED BY THE REGENTS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE REGENTS AND CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

#ifndef _RTS_CAMERA_ZOOM_H
#define _RTS_CAMERA_ZOOM_H

#include "linux/rts_camera_isp_info.h"

enum {
	RTSCAM_ZOOM_EVT_DYN_FPS_CHANGED = 0,
	RTSCAM_ZOOM_EVT_COLOR_RANGE_CHANGED = 1,
	RTSCAM_ZOOM_EVT_RESERVED
};

struct rtscam_zoom_isp {
	struct device *dev;
	struct rts_isp_info info;

	int (*set_fps)(struct rtscam_zoom_isp *isp, struct v4l2_fract fps);
	int (*set_hook)(struct rtscam_zoom_isp *isp, void *master,
			int (*hook)(void *master, int id, void *arg));

	void *master;
};

int rtscam_zoom_register_isp(struct rtscam_zoom_isp *isp);
int rtscam_zoom_unregister_isp(struct rtscam_zoom_isp *isp);
int rtscam_zoom_refresh_isp_info(struct rtscam_zoom_isp *isp,
	int force_reset);

#endif
