#include "rts_xb2_timer.h"

void rts_xb2_timer_enable(struct timer_node *ptimer, struct xb2_timer_reg *reg)
{
    MS_DEBUG("====timer enabled period %dms ===", ptimer->timer_period / 25 / 1000);
    //When the counter runs equal to compare counter, an interrupt occurs.
	writel(ptimer->timer_period, ptimer->io_base + reg->rts_timer0_compare);
    //timer mode, 00: Oneshot mode, 01: Periodic
	writel(MODE_PERIODIC, ptimer->io_base + reg->rts_timer0_mode);
    //Enable XB2_TIMER0 timer. Setting 0 will clear the current counterto 0. Setting 1 the current counter increase at 25MHz.
	writel(0x01, ptimer->io_base + reg->rts_timer0_en);
    //Enable the xb2 timer0 interrupt while setting 1
    writel(0x01, ptimer->io_base + reg->rts_timer0_int_en);
}

int rts_xb2_timer_int_sts(struct timer_node *ptimer, struct xb2_timer_reg *reg)
{
    //When the counter runs equal to compare counter, an interrupt occurs, this bit will be set 1.
    //For a shared interrupt line, determine whether the interrupt is generated by the hardware corresponding to the interrupt handler
    return readl(ptimer->io_base + reg->rts_timer0_int_sts) & 0x01;
}

void rts_xb2_timer_clr_int_sts(struct timer_node *ptimer, struct xb2_timer_reg *reg)
{
    //Writing 0x01 indicates that the interrupt is handled by this interrupt handler
    writel(0x01, ptimer->io_base + reg->rts_timer0_int_sts);
}

void rts_xb2_timer_disable(struct timer_node *ptimer, struct xb2_timer_reg *reg)
{
    MS_DEBUG("====timer disabled===");
    //timer interrupt disable
    writel(0x0, ptimer->io_base + reg->rts_timer0_int_en);
    //timer disable
	writel(0x0, ptimer->io_base + reg->rts_timer0_en);
    //timer_period reset to 0
	ptimer->timer_period = 0;
}
