/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (c) 2025 Realtek Semiconductor Corp. All rights reserved.
 *
 * THIS SOFTWARE IS CONFIDENTIAL AND PROPRIETARY TO REALTEK SEMICONDUCTOR
 * CORP. DISCLOSURE, REPRODUCTION, REDISTRIBUTION, IN WHOLE OR IN PART, OF
 * THIS WORK AND ITS DERIVATIVES WITHOUT EXPRESS PERMISSION IS PROHIBITED.
 *
 * REALTEK SEMICONDUCTOR CORP. RESERVES THE RIGHT TO UPDATE, MODIFY, OR
 * DISCONTINUE THIS SOFTWARE AT ANY TIME WITHOUT NOTICE. THIS SOFTWARE IS
 * PROVIDED BY THE REGENTS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE REGENTS AND CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

#ifndef __SND_SOC_RTS_CODEC_H
#define __SND_SOC_RTS_CODEC_H

#define RTS_REG_TCON_CFG		0x00
#define RTS_REG_DAC_CFG			0x10
#define RTS_REG_DAC_PDM_DFG		0x14
#define RTS_REG_ADC_CFG1		0x20
#define RTS_REG_ADC_CFG2		0x24
#define RTS_REG_ADC2_CFG1		0x28
#define RTS_REG_ADC2_CFG2		0x2C
#define RTS_REG_ADDA_ANA_CFG1		0x40
#define RTS_REG_ADDA_ANA_CFG2		0x44
#define RTS_REG_ADDA_ANA_CFG3		0x48
#define RTS_REG_ADDA_ANA_CFG4		0x4C
#define RTS_REG_AGC_CFG1		0x60
#define RTS_REG_AGC_CFG2		0x64
#define RTS_REG_AGC_CFG3		0x68
#define RTS_REG_AGC_CFG4		0x6C
#define RTS_REG_AGC_CFG5		0x70
#define RTS_REG_AGC_CFG6		0x74
#define RTS_REG_AGC2_CFG1		0x78
#define RTS_REG_AGC2_CFG2		0x7C
#define RTS_REG_ALC_PGA_CFG1		0x90
#define RTS_REG_ALC_PGA_CFG2		0x94
#define RTS_REG_ALC_PGA_CFG3		0x98
#define RTS_REG_ALC_PGA_CFG4		0x9C
#define RTS_REG_ALC_PGA_CFG5		0xa0
#define RTS_REG_ALC_PGA_CFG6		0xa4

/* RTS_REG_DAC_CFG */
#define RTS_DAAD_LP_EN			26
#define RTS_DAHPF_EN			25
#define RTS_DA_GAIN_L			18
#define RTS_DA_GAIN_R			11
#define RTS_DA_MUTE_L			10
#define RTS_DA_MUTE_R			9
#define RTS_DA_RST_N			1
#define RTS_DAMOD_RST_N			0

/* RTS_REG_DAC_PDM_DFG */
#define RTS_SDM_RST_N			6

/* RTS_REG_ADC_CFG1 */
#define RTS_AD_COMP_GAIN		25
#define RTS_AD_GAIN_L			18
#define RTS_AD_GAIN_R			11
#define RTS_AD_MUTE_L			10
#define RTS_AD_MUTE_R			9
#define RTS_DMIC_BOOST_GAIN_L		3
#define RTS_DMIC_BOOST_GAIN_R		1
#define RTS_AD_RST_N			0

/* RTS_REG_ADC_CFG2 */
#define RTS_DMIC_MIX_MUTE_L		11
#define RTS_DMIC_MIX_MUTE_R		10
#define RTS_AD_MIX_MUTE_L		1
#define RTS_AD_MIX_MUTE_R		0

/* RTS_REG_AGC_CFG5 */
#define RTS_ALC_BK_GAIN_L		19
#define RTS_ALC_BK_GAIN_R		13
#define RTS_ALC_FT_BOOST		0

/* RTS_REG_TCON_CFG */
#define RTS_DMIC2_CLK_EN			11
#define RTS_AD2_CLK_EN			10
#define RTS_AUDIO_IP_TCON_RST_N		9
#define RTS_ADC_SAMPLE_RATE		23
#define RTS_DAC_SAMPLE_RATE		16
#define RTS_DA_CLK_EN			4
#define RTS_DMIC_CLK_EN			3
#define RTS_AD_CLK_EN			2
#define RTS_AD_ANA_CLK_EN		1
#define RTS_PDM_CLK_EN			0

/* RTS_REG_ADDA_ANA_CFG1 */
#define RTS_POW_DACVREF			20
#define RTS_POW_DEPOP			19
#define RTS_POW_DEPOP_CK		18
#define RTS_POW_DEPOP_OP		17
#define RTS_POW_MBIAS			16
#define RTS_POW_VCM			15
#define RTS_POW_ADCL			14
#define RTS_POW_ADCR			13
#define RTS_POW_AFEL			12
#define RTS_POW_AFER			11
#define RTS_POW_DACL			10
#define RTS_POW_DACR			9
#define RTS_POW_IBFL			8
#define RTS_POW_IBFR			7
#define RTS_POW_LOL			6
#define RTS_POW_LOR			5
#define RTS_POW_MICBIAS			4
#define RTS_POW_MICL			3
#define RTS_POW_MICR			2
#define RTS_POW_OC			1
#define RTS_POW_ZCD			0

/* RTS_REG_ADDA_ANA_CFG2 */
#define RTS_CUR_DEPOP			30
#define RTS_DEPOP_CAP_SEL		28
#define RTS_VCM_READY			27
#define RTS_VCM_SEL			25
#define RTS_RAMP_OUT_CTRL		24
#define RTS_AFEL_GAIN			22
#define RTS_AFER_GAIN			20
#define RTS_CHX_FREQ_ADC		18
#define RTS_CHX_FREQ_DAC		16
#define RTS_CHX_FREQ_MICB		14
#define RTS_CUR_ADC			12
#define RTS_CUR_AFE			10
#define RTS_CUR_DAC			8
#define RTS_CUR_IBF			6
#define RTS_CUR_LO			4
#define RTS_CUR_MIC			2
#define RTS_CUR_MICBIAS			0

/* RTS_REG_ADDA_ANA_CFG3 */
#define RTS_CUR_VREF			30
#define RTS_CUR_ZCD			28
#define RTS_EN_CHX_DAC			27
#define RTS_EN_CHX_ADC			26
#define RTS_EN_CHX_MICB			25
#define RTS_MUTE_L			10
#define RTS_MUTE_R			9
#define RTS_MUX_L			7
#define RTS_MUX_R			5
#define RTS_NORM			4
#define RTS_OCSEL			2
#define RTS_QRES			0

/* RTS_REG_ADDA_ANA_CFG4 */
#define RTS_SELIN			9
#define RTS_LOL_GAIN			7
#define RTS_LOR_GAIN			5

/* RTS_REG_ALC_PGA_CFG4 */
#define RTS_MICL_GAIN			7
#define RTS_MICR_GAIN			0

enum {
	RTS_CODEC_ANALOG,
	RTS_CODEC_DIGITAL,
};

enum {
	RTS_CODEC_MONO_LEFT_IN,
	RTS_CODEC_MONO_RIGHT_IN,
};

enum {
	RTS_CODEC_MONO_LEFT_OUT,
	RTS_CODEC_MONO_RIGHT_OUT,
};

#define RTS_CODEC_RATES		(SNDRV_PCM_RATE_8000 |\
				 SNDRV_PCM_RATE_11025 |\
				 SNDRV_PCM_RATE_16000 |\
				 SNDRV_PCM_RATE_22050 |\
				 SNDRV_PCM_RATE_32000 |\
				 SNDRV_PCM_RATE_44100 |\
				 SNDRV_PCM_RATE_48000 |\
				 SNDRV_PCM_RATE_88200 |\
				 SNDRV_PCM_RATE_96000 |\
				 SNDRV_PCM_RATE_176400 |\
				 SNDRV_PCM_RATE_192000 |\
				 SNDRV_PCM_RATE_KNOT)

#define RTS_CODEC_FORMATS	(SNDRV_PCM_FMTBIT_U8 |\
				 SNDRV_PCM_FMTBIT_S16_LE |\
				 SNDRV_PCM_FMTBIT_S24_3LE)

struct rts_codec_data {
	struct platform_device *pdev;
	struct reset_control *rst;
	struct snd_pcm_substream *substream[2];
	void __iomem *addr;
	u32 devtype;
	struct clk *codec_clk;
	int codec_ref;
	struct mutex codec_mutex;
	int channels;
	int mono_in_mode;
	int mono_out_mode;
};

#endif
