/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (c) 2025 Realtek Semiconductor Corp. All rights reserved.
 *
 * THIS SOFTWARE IS CONFIDENTIAL AND PROPRIETARY TO REALTEK SEMICONDUCTOR
 * CORP. DISCLOSURE, REPRODUCTION, REDISTRIBUTION, IN WHOLE OR IN PART, OF
 * THIS WORK AND ITS DERIVATIVES WITHOUT EXPRESS PERMISSION IS PROHIBITED.
 *
 * REALTEK SEMICONDUCTOR CORP. RESERVES THE RIGHT TO UPDATE, MODIFY, OR
 * DISCONTINUE THIS SOFTWARE AT ANY TIME WITHOUT NOTICE. THIS SOFTWARE IS
 * PROVIDED BY THE REGENTS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE REGENTS AND CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

#ifndef __SND_SOC_RTS_DMA_H
#define __SND_SOC_RTS_DMA_H

#define RTS_COMMON_FORMAT_SHIFT			2

#define RTS_REG_RX_FIFO_THRESHOLD		0x00
#define RTS_REG_TX_FIFO_THRESHOLD		0x04
#define RTS_REG_RX_SA				0x08
#define RTS_REG_RX_LEN				0x0C
#define RTS_REG_RX_RP				0x10
#define RTS_REG_RX_WP				0x14
#define RTS_REG_TX_SA				0x18
#define RTS_REG_TX_LEN				0x1C
#define RTS_REG_TX_RP				0x20
#define RTS_REG_TX_WP				0x24
#define RTS_REG_FIFO_ENABLE			0x28
#define RTS_REG_FIFO_CTL			0x2C
#define RTS_REG_AUDIO_CTL			0x30
#define RTS_REG_RX_BUFFER_THRESHOLD		0x34
#define RTS_REG_RX_TIMER_COUNT			0x38
#define RTS_REG_RX_TIMER_THRESHOLD		0x3C
#define RTS_REG_TX_BUFFER_THRESHOLD		0x40
#define RTS_REG_TX_TIMER_COUNT			0x44
#define RTS_REG_TX_TIMER_THRESHOLD		0x48
#define RTS_REG_AUDIO_INT_EN			0x4C
#define RTS_REG_AUDIO_INT_STS			0x50
#define RTS_REG_RX_FIFO_STATUS			0x54
#define RTS_REG_TX_FIFO_STATUS			0x58
#define RTS_REG_FIFO_ACCESS_ADDR		0x5C
#define RTS_REG_FIFO_ACCESS_DATA		0x60

/* in volume detect register */
#define RTS_REG_IN_VOLUME_DETECT_THRESHOLD			0x100
#define RTS_REG_IN_VOLUME_DETECT_PARAM				0x104
#define RTS_REG_IN_VOLUME_DETECT_RESULT0			0x108
#define RTS_REG_IN_VOLUME_DETECT_RESULT1			0x10c

/* RTS_REG_RX_SA */
#define RTS_BIT_RX_SA				(0)

/* RTS_REG_RX_RP */
#define RTS_BIT_RX_RP				(0)

/* RTS_REG_RX_WP */
#define RTS_BIT_RX_WP				(0)

/* RTS_REG_TX_SA */
#define RTS_BIT_TX_SA				(0)

/* RTS_REG_TX_RP */
#define RTS_BIT_TX_RP				(0)

/* RTS_REG_TX_WP */
#define RTS_BIT_TX_WP				(0)

/* RTS_REG_FIFO_ENABLE */
#define RTS_BIT_TX_FIFO_ENABLE			(0)
#define RTS_BIT_RX_FIFO_ENABLE			(1)

/* RTS_REG_FIFO_CTL */
#define RTS_BIT_TX_FIFO_FLUSH			(0)
#define RTS_BIT_RX_FIFO_FLUSH			(1)

/* RTS_REG_AUDIO_CTL */
#define RTS_BIT_IN_SOURCE_SELECT		(0)
#define RTS_BIT_AUDIO_IN_MODE			(2)
#define RTS_BIT_AUDIO_OUT_MODE			(5)
#define RTS_BIT_IN_DATA_WIDTH			(7)
#define RTS_BIT_OUT_DATA_WIDTH			(9)
#define RTS_BIT_OUT_SOURCE_SELECT		(11)
#define RTS_BIT_IN_OUT_LOOPBACK			(13)
#define RTS_BIT_AUDIO_IN_MODE1			(16)
#define RTS_BIT_IN_DATA_WIDTH1			(19)
#define RTS_BIT_AUDIO_IN_C0_EN			(21)
#define RTS_BIT_AUDIO_IN_C1_EN			(22)

/* RTS_REG_RX_TIMER_THRESHOLD */
#define RTS_BIT_AUDIO_IN_TIMER_EN		(20)

/* RTS_REG_TX_TIMER_THRESHOLD */
#define RTS_BIT_AUDIO_OUT_TIMER_EN		(20)

/* RTS_REG_AUDIO_INT_STS */
#define RTS_BIT_AUDIO_IN_TIMER			(0)
#define RTS_BIT_AUDIO_IN_DDR_THRESHOLD		(1)
#define RTS_BIT_AUDIO_IN_FIFO_FULL		(2)
#define RTS_BIT_AUDIO_IN_DDR_FULL		(3)
#define RTS_BIT_AUDIO_OUT_TIMER			(4)
#define RTS_BIT_AUDIO_OUT_DDR_THRESHOLD		(5)
#define RTS_BIT_AUDIO_OUT_FIFO_EMPTY		(6)
#define RTS_BIT_AUDIO_OUT_DDR_EMPTY		(7)
#define RTS_BIT_OCP_READ_ERR			(8)
#define RTS_BIT_IN_VOLUME_DETECT_INT_C0		(11)
#define RTS_BIT_IN_VOLUME_DETECT_INT_C1		(12)

/*RTS_REG_IN_VOLUME_DETECT_THRESHOLD*/
#define RTS_BIT_IN_VOLUME_THD_C0		(0)
#define RTS_BIT_IN_VOLUME_THD_C1		(16)

/*RTS_REG_IN_VOLUME_DETECT_PARAM*/
#define RTS_BIT_IN_VOLUME_PARAM_C0		(0)
#define RTS_BIT_ADF_VOL_DEF_SEL_C0		(8)
#define RTS_BIT_IN_VOLUME_PARAM_C1		(16)
#define RTS_BIT_ADF_VOL_DEF_SEL_C1		(24)

/*RTS_REG_IN_VOLUME_DETECT_RESULT0*/
#define RTS_BIT_IN_VOLUME_R_RESULT_C0		(0)
#define RTS_BIT_IN_VOLUME_L_RESULT_C0		(16)
#define RTS_BIT_IN_VOLUME_RESULT_CLR_C0		(31)

/*RTS_REG_IN_VOLUME_DETECT_RESULT1*/
#define RTS_BIT_IN_VOLUME_R_RESULT_C1		(0)
#define RTS_BIT_IN_VOLUME_L_RESULT_C1		(16)
#define RTS_BIT_IN_VOLUME_RESULT_CLR_C1		(31)

#define RTS_SND_DMA_TIMER_IN			0
#define RTS_SND_DMA_TIMER_OUT			1

enum {
	RTS_SND_DMA_NORMAL_STEREO_OUT,
	RTS_SND_DMA_EXCHANGE_STEREO_OUT,
	RTS_SND_DMA_MONO_OUT,
	RTS_SND_DMA_MONO_TO_STEREO_OUT,
	RTS_SND_DMA_NORMAL_STEREO_IN,
	RTS_SND_DMA_EXCHANGE_STEREO_IN,
	RTS_SND_DMA_MONO_LEFT_IN,
	RTS_SND_DMA_MONO_RIGHT_IN,
	RTS_SND_DMA_MONO_MIX_IN,
};

struct rts_dma_subdata {
	struct snd_pcm_substream *substream;
	int format;
	int codec_sel;
	int mono_mode;
	int stereo_mode;
};

struct rts_dma_data {
	struct platform_device *pdev;
	struct reset_control *sysmem_sd;
	void __iomem *addr;
	int irq;
	int runflag[2];
	struct rts_dma_subdata subdata[2];
	struct snd_dma_buffer dma_buf[2];
	u32 devtype;
	int channels;
};

#endif /* __SND_SOC_RTS_DMA_H */
