/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (c) 2025 Realtek Semiconductor Corp. All rights reserved.
 *
 * THIS SOFTWARE IS CONFIDENTIAL AND PROPRIETARY TO REALTEK SEMICONDUCTOR
 * CORP. DISCLOSURE, REPRODUCTION, REDISTRIBUTION, IN WHOLE OR IN PART, OF
 * THIS WORK AND ITS DERIVATIVES WITHOUT EXPRESS PERMISSION IS PROHIBITED.
 *
 * REALTEK SEMICONDUCTOR CORP. RESERVES THE RIGHT TO UPDATE, MODIFY, OR
 * DISCONTINUE THIS SOFTWARE AT ANY TIME WITHOUT NOTICE. THIS SOFTWARE IS
 * PROVIDED BY THE REGENTS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE REGENTS AND CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

#ifndef __SND_SOC_RTS_I2S_H
#define __SND_SOC_RTS_I2S_H

#define RTS_I2S_DIV_BCLK		0
#define RTS_I2S_DIV_MCLK		1
#define RTS_I2S_DIV_MCLK_PC		2

#define RTS_I2S_CODEC_PC		0
#define RTS_I2S_CODEC_CE_256FS		1
#define RTS_I2S_CODEC_CE_512FS		2

/* i2s reg */
#define RTS_REG_I2S_CTL			0x0
#define RTS_REG_I2S_CFG			0x4

/* i2s power reg */
#define RTS_REG_I2S_OCP_CTL		0x8
#define RTS_REG_I2S_OCP_CFG		0xc

/* spdif cfg reg */
#define RTS_REG_SPDIF_CFG		0x100

/* RTS_REG_I2S_CTL */
#define RTS_I2S_IN_GO			(0)
#define RTS_I2S_OUT_GO			(1)
#define RTS_EN_I2S_MONO			(2)
#define RTS_I2S_LJ_MODE_SEL		(3)
#define RTS_I2S_LJ_MONO_MODE_SEL	(4)
#define RTS_TDM_SELF_LPBK_EN		(5)
#define RTS_I2S_SCK_OE			(6)
#define RTS_I2S_WS_OE			(7)
#define RTS_SCK_GEN_SEL			(15)
#define RTS_BCLK_INT_DIV		(16)
#define RTS_MCLK_DIV_SEL		(24)
#define RTS_I2S_SAMPLE_RATE		(28)

/* RTS_REG_I2S_CFG */
#define RTS_TDM_RW_PULSE_WD_SEL		(0)
#define RTS_TCON_TDM_LRCK_SEL		(1)
#define RTS_TCON_TDM_BCLK_SEL		(3)
#define RTS_TCON_CHANNEL_LENGTH		(6)
#define RTS_TCON_SEL_I2S_DATA_FORMAT	(8)
#define RTS_TCON_LRCK_PULSE_SEL		(11)
#define RTS_SEL_I2S_FORMAT		(12)
#define RTS_INV_TDM_LRCK_MST		(15)
#define RTS_INV_TDM_LRCK		(16)
#define RTS_INV_TDM_BCLK_MST		(17)
#define RTS_INV_TDM_BCLK		(18)
#define RTS_SEL_I2S_DATA_LEN		(19)

/* RTS_REG_I2S_OCP_CTL */
#define RTS_LDOI2S_POW			(0)

/* RTS_REG_I2S_OCP_CFG */
#define RTS_REG_TUNE_VO		(0)

/*RTS_REG_SPDIF_CFG*/
#define RTS_BIT_SPDIF_FORCE_ZERO_SPO			(0)
#define RTS_BIT_SPDIF_ZEROB_DATA				(1)
#define RTS_BIT_SPDIF_OUT_AUDIO_TYPE			(2)
#define RTS_BIT_SPDIF_OUT_COPY				(3)
#define RTS_BIT_SPDIF_OUT_EN					(4)
#define RTS_BIT_SPDIF_OUT_PRE					(5)
#define RTS_BIT_SPDIF_OUT_PRO					(6)
#define RTS_BIT_SPDIF_OUT_VALID				(7)
#define RTS_BIT_SPDIF_OUT_VCFG				(8)
#define RTS_BIT_SPDIF_OUT_LEVEL				(9)
#define RTS_BIT_SPDIF_BITS						(10)
#define RTS_BIT_SPDIF_SR						(13)
#define RTS_BIT_SPDIF_OUT_CC					(16)

#define RTS_I2S_RATES	(SNDRV_PCM_RATE_8000 |\
			SNDRV_PCM_RATE_11025 |\
			SNDRV_PCM_RATE_16000 |\
			SNDRV_PCM_RATE_22050 |\
			SNDRV_PCM_RATE_32000 |\
			SNDRV_PCM_RATE_44100 |\
			SNDRV_PCM_RATE_48000 |\
			SNDRV_PCM_RATE_88200 |\
			SNDRV_PCM_RATE_96000 |\
			SNDRV_PCM_RATE_176400 |\
			SNDRV_PCM_RATE_192000 |\
			SNDRV_PCM_RATE_KNOT)

#define RTS_I2S_FORMATS	(SNDRV_PCM_FMTBIT_U8 |\
			 SNDRV_PCM_FMTBIT_S16_LE |\
			 SNDRV_PCM_FMTBIT_S24_3LE)

#define RTS_SPDIF_RATES	(SNDRV_PCM_RATE_48000 |\
			SNDRV_PCM_RATE_96000 |\
			SNDRV_PCM_RATE_192000 |\
			SNDRV_PCM_RATE_44100 |\
			SNDRV_PCM_RATE_88200 |\
			SNDRV_PCM_RATE_176400 |\
			SNDRV_PCM_RATE_KNOT)

#define RTS_SPDIF_FORMATS	(SNDRV_PCM_FMTBIT_S16_LE |\
			 SNDRV_PCM_FMTBIT_S24_3LE |\
			 SNDRV_PCM_FMTBIT_S20_3LE)

struct rts_i2s_dai_data {
	struct platform_device *pdev;
	struct reset_control *spdif_rst;
	struct reset_control *i2s_rst;
	struct snd_pcm_substream *substream[2];
	void __iomem *addr;

	struct clk *i2s_clk;
	struct clk *spdif_clk;
	int spdif_ref;
	struct mutex spdif_mutex;
	int clk_ref;
	struct mutex clk_mutex;
	int ldoi2s_ref;
	struct mutex ldoi2s_mutex;
	int channels;
	u32 devtype;
};

#ifdef CONFIG_SND_SOC_RTS_RT5677
void rts_i2s_clock_disable(struct snd_soc_dai *dai);
#endif

#endif /* __SND_SOC_RTS_I2S_H */
