USB_MULTI_SITE_METHOD = local
USB_MULTI_DEPENDENCIES += $(if $(BR2_PACKAGE_UVCD),rtstream ubus json-c realbox)
USB_MULTI_DEPENDENCIES += $(if $(BR2_PACKAGE_DFUD),mtd)
USB_MULTI_DEPENDENCIES += $(if $(BR2_PACKAGE_OSD_SUPPRT),freetype)
USB_MULTI_BIN_TARGET = $(USB_BIN_TARGET)/usb_multi
ifneq ($(BR2_PACKAGE_CONFIGFS),y)
define USB_MULTI_REMOVE_CFG
rm -rf $(TARGET_DIR)/usr/bin/configfs.sh
endef
USB_MULTI_POST_INSTALL_TARGET_HOOKS += USB_MULTI_REMOVE_CFG
endif

