#!/bin/sh
#
# Run the preinit scripts
#

start() {
	# if test -e "/sys/bus/platform/devices/soc:leds/leds/bt_reset" ; then
	# 	echo 0 > /sys/bus/platform/devices/soc:leds/leds/bt_reset/brightness
	# 	sleep 0.03
	# 	echo 1 > /sys/bus/platform/devices/soc:leds/leds/bt_reset/brightness
	# fi

	find /sys/bus/usb/devices -type f -name 'uevent' -maxdepth 3 -follow \
		| while read dev_event; do
		echo add > $dev_event;
        done

	#preinit script
        if [ -d /app/rt/preinit ]; then
                for pi_source_file in /app/rt/preinit/*; do
                        . $pi_source_file
                done
        fi

	#set sys_tz
        if [ -x /sbin/hwclock ]; then
                hwclock -u --systz
        fi
}

stop() {
	:
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        stop
        start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
