/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (c) 2025 Realtek Semiconductor Corp. All rights reserved.
 *
 * THIS SOFTWARE IS CONFIDENTIAL AND PROPRIETARY TO REALTEK SEMICONDUCTOR
 * CORP. DISCLOSURE, REPRODUCTION, REDISTRIBUTION, IN WHOLE OR IN PART, OF
 * THIS WORK AND ITS DERIVATIVES WITHOUT EXPRESS PERMISSION IS PROHIBITED.
 *
 * REALTEK SEMICONDUCTOR CORP. RESERVES THE RIGHT TO UPDATE, MODIFY, OR
 * DISCONTINUE THIS SOFTWARE AT ANY TIME WITHOUT NOTICE. THIS SOFTWARE IS
 * PROVIDED BY THE REGENTS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE REGENTS AND CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

#ifndef _PM_RTS3917_H_
#define _PM_RTS3917_H_

/* SRAM */
#define SRAM_BASE	0x19000000
#define SRAM_SIZE	0x1a800

/* DDR controller */
#define DDRC_BASE	0x18010000
#define DDRC_SIZE	0x3000

#define DDRC_CCR_REG			0x0
#define DDRC_IOCR_REG			0x8
#define DDRC_CSR_REG			0xC
#define DDRC_DRR_REG			0x10
#define DDRC_TPR0_REG			0x14
#define DDRC_CMD_DPIN_NDGE_REG		0x24
#define DDRC_CMD_DPIN_REG		0x28
#define DDRC_TIE_DPIN_REG		0x2C

/* DDR PHY */
#define DDRP_BASE	0x18080000
#define DDRP_SIZE	0x600

#define DDRP_PLL_CTL0_REG		0x4
#define DDRP_PLL_CTL1_REG		0x8
#define DDRP_CRT_RST_CTL_REG		0x8C

#define DDRP_PAD_OE_CTL_REG		0x114
#define PAD_OE_CTL_EN			0x9fffffff
#define PAD_OE_CTL_DIS			0x04200000

#define DDRP_PAD_OE_CTL_EX_REG		0x118
#define PAD_OE_CTL_EXT_EN		0x0003ff07
#define PAD_OE_CTL_EXT_DIS		0x0

#define DDRP_PAD_BUS_0_REG		0x1F4
#define CK_PD_BIT			0x40000000

#define DDRP_PAD_BUS_1_REG			0x1F8
#define ZQ_PD_BIT			0x40

#define DDRP_READ_DBG_CTRL_SET0_REG	0x508
#define DDRP_READ_DBG_CTRL_SET1_REG	0x50c
#define DQS_DQ_DM_PD			0x3ff
#define DQS_DM_PD			0x300

/* MISC */
#define MISC_BASE	0x18860000
#define MISC_SIZE	0x30

#define SYS_DDR_STATUS_REG		0x10
#define SYS_DDR_PHYCFG_REG		0x24

/* GPLL */
#define GPLL_BASE	0x188b0000
#define GPLL_SIZE	0x400

#define GPLL0_OFFSET	0x0
#define GPLL1_OFFSET	0x100
#define GPLL2_OFFSET	0x200

#define GPLL_CTRL_REG			0x0
#define GPLL_CFG_REG			0x4
#define GPLL_SCCG_CFG0_REG		0x8
#define GPLL_SCCG_CFG1_REG		0xC
#define GPLL_STATUS_REG			0x10
#define GPLL_SCCG_CFG3_RRG		0x18

/* CLOCK */
#define CLOCK_BASE	0x188d0000
#define CLOCK_SIZE	0x1000

#define CLK_ENABLE	0x1000000

#define CLK_CHANGE_REG			0x0
#define UART_CLK_LP_EN_REG		0x04
#define P1BUS_CLK_CFG_REG		0x08
#define DRAM_CLK_CFG_REG		0x0c
#define CPU_CLK_CFG_REG			0x10
#define XB2_CLK_CFG_REG			0x14
#define BUS_CLK_CFG_REG			0x18
#define I2S_CLK_CFG_REG			0x1c
#define CIPHER_CLK_CFG_REG		0x20
#define UART_CLK_CFG_REG		0x28
#define I2C_CLK_CFG_REG			0x2c

#define RTC32K_DIV_CFG0_REG		0x3c
#define RTC32K_DIV_CFG1_REG		0x40
#define RTC32K_DIV_CFG2_REG		0x44
#define RTC_CLK_CFG_REG			0x48
#define USBPHY_CLK_CFG_REG		0x4c
#define JPEG_CLK_CFG_REG		0x50

#define ISP_SCAN_CLK_CFG_REG		0x58
#define MIPI_SCAN_CLK_CFG_REG		0x5c
#define SPDIF_CLK_CFG_REG		0x60

#define CODEC_CLK_CFG_REG		0x68

#define GE_CLK_EN_REG			0x78
#define BWT_CLK_EN_REG			0x7c
#define H265_ACLK_CFG_REG		0x80
#define H265_BCLK_CFG_REG		0x84
#define H265_CCLK_CFG_REG		0x88
#define SSOR_HCLK_CFG_REG		0x8C
#define SSOR_CLK_OE_REG			0x90
#define RSA_CLK_EN_REG			0xA0
#define SHA_CLK_EN_REG			0xA4
#define NN_BUS_CLK_CFG_REG		0xB0
#define NN_CORE_CLK_CFG_REG		0xB4
#define NN_SH_CLK_CFG_REG		0xB8
#define TRNG_CLK_CFG_REG		0xBC
#define LCDC_DRAM_CLK_CFG_REG		0xC0
#define ETHERNET_CLK_CFG_REG		0xC4
#define EFUSE_CLK_CFG_REG		0xC8
#define MAC_BYPASS_CLK_CFG_REG		0xCC
#define JPEG_DRAM_CLK_CFG_REG		0xD0
#define MIPI_TX_CFG_REG			0xD4
#define DMA_CLK_CFG_REG			0xD8
#define MIPI_TX_LOW_CLK_CFG_REG		0xDC
#define SD0_CRC_CLK_CFG_REG		0xE0
#define SD0_SAMPLE_CLK_CFG_REG		0xE4
#define SD0_PUSH_CLK_CFG_REG		0xE8
#define SD0_DDR_CLK_CFG_REG		0xEC
#define SD1_CRC_CLK_CFG_REG		0xF0
#define SD1_SAMPLE_CLK_CFG_REG		0xF4
#define SD1_PUSH_CLK_CFG_REG		0xF8
#define SD1_DDR_CLK_CFG_REG		0xFC

#define UART1_CLK_CFG_REG		0x104
#define UART2_CLK_CFG_REG		0x108
#define I2C1_CLK_CFG_REG		0x10C
#define ISP_ZOOM_CLK_CFG_REG		0x110
#define CPU_TRC_CLK_CFG_REG		0x114
#define SSI_CLK_CFG_REG			0x118

/* RESET */
#define RESET_BASE	0x188d8000
#define RESET_SIZE	0x1000

#define FORCE_REG_RST_FWC_REG		0x04
#define FORCE_DRAM_LCDC_RESET		BIT(13)
#define FORCE_BUS_SHA256_RESET		BIT(12)
#define FORCE_DRAM_RSA_RESET		BIT(11)
#define FORCE_DRAM_H265PP_RESET		BIT(10)
#define FORCE_FEPHY_RESET		BIT(5)
#define FORCE_LCDC_RESET		BIT(4)
#define FORCE_RTC32K_RESET		BIT(3)
#define FORCE_U2DEV_UTMI_RESET		BIT(2)
#define FORCE_U2HOST_UTMI_RESET		BIT(1)

#define FORCE_REG_ASYNC_RST_REG		0x08
#define FORCE_SSI_ASYNC_RESET		BIT(25)
#define FORCE_ZOOM_ISP_CLK_ASYNC_RESET	BIT(24)
#define FORCE_UART2_CLK_ASYNC_RESET	BIT(23)
#define FORCE_UART1_CLK_ASYNC_RESET	BIT(22)
#define FORCE_MIPI_TX_CLK_ASYNC_RESET	BIT(21)
#define FORCE_DRAM_JPG_CLK_ASYNC_RESET	BIT(20)
#define FORCE_NN_CORE_CLK_ASYNC_RESET	BIT(19)
#define FORCE_DRAM_NN_CLK_ASYNC_RESET	BIT(18)
#define FORCE_OTP_CLK_ASYNC_RESET	BIT(17)
#define FORCE_TRNG_CLK_ASYNC_RESET	BIT(16)
#define FORCE_SD1_CLK_ASYNC_RESET	BIT(15)
#define FORCE_H265_CCLK_ASYNC_RESET	BIT(14)
#define FORCE_H265_BCLK_ASYNC_RESET	BIT(13)
#define FORCE_H265_ACLK_ASYNC_RESET	BIT(12)
#define FORCE_CODEC_CLK_ASYNC_RESET	BIT(11)
#define FORCE_SPDIF_CLK_ASYNC_RESET	BIT(10)
#define FORCE_I2C1_CLK_ASYNC_RESET	BIT(9)
#define FORCE_I2C0_CLK_ASYNC_RESET	BIT(8)
#define FORCE_UART0_CLK_ASYNC_RESET	BIT(7)
#define FORCE_ETHERNET_CLK_ASYNC_RESET	BIT(6)
#define FORCE_SD0_CLK_ASYNC_RESET	BIT(5)
#define FORCE_CIPHER_CLK_ASYNC_RESET	BIT(4)
#define FORCE_I2S_CLK_ASYNC_RESET	BIT(3)
#define FORCE_ISP_CLK_ASYNC_RESET	BIT(2)
#define FORCE_JPG_CLK_ASYNC_RESET	BIT(1)
#define FORCE_MIPI_CLK_ASYNC_RESET	BIT(0)

/* USB PHY */
#define USBPHY_BASE	0x18140000
#define USBPHY_SIZE	0x50

#define U2_APHY_CFG4_REG		0x10

/* WATCHDOG */
#define WATCHDOG_BASE	0x188da000
#define WATCHDOG_SIZE	0x10

#define WATCHDOG_CFG_REG	0x0
#define WATCHDOG_EN		0x1

#ifndef __ASSEMBLY__

#ifdef CONFIG_RTSX_WATCHDOG
extern unsigned int g_wdt_flag;
#endif

#endif

#endif /* _PM_RTS3917_H_ */
