/* SPDX-License-Identifier: GPL-2.0+ */
/*
 *	f_uvc.h  --  USB Video Class Gadget driver
 *
 *	Copyright (C) 2009-2010
 *	    Laurent Pinchart (laurent.pinchart@ideasonboard.com)
 */

#ifndef _F_UVC_H_
#define _F_UVC_H_

#include <linux/usb/video.h>

#include "uvc.h"
struct uvc_device;

#define VS_UNDEFINED		0x00
#define VS_INPUT_HEADER		0x01
#define VS_OUTPUT_HEADER	0x02
#define VS_STILL_IMAGE_FRAME	0x03
#define VS_FORMAT_UNCOMPRESSED	0x04
#define VS_FRAME_UNCOMPRESSED	0x05
#define VS_FORMAT_MJPEG		0x06
#define VS_FRAME_MJPEG		0x07
#define VS_FORMAT_MPEG2TS	0x0A
#define VS_FORMAT_DV		0x0C
#define VS_COLORFORMAT		0x0D
#define VS_FORMAT_VENDOR	0x0E
#define VS_FRAME_VENDOR		0x0F
#define VS_FORMAT_FRAME_BASED	0x10
#define VS_FRAME_FRAME_BASED	0x11
#define VS_FORMAT_STREAM_BASED	0x12
#define VS_FORMAT_H264		0x13
#define VS_FRAME_H264		0x14

#define RATE_CONTROL_VBR_MODE			0x01
#define RATE_CONTROL_CBR_MODE			0x02
#define RATE_CONTROL_CONSTANT_QP_MODE		0x03
#define RATE_CONTROL_GVBR_MODE			0x04
#define RATE_CONTROL_VBRN_MODE			0x05
#define RATE_CONTROL_GVBRN_MODE			0x06

#define H264_INTER_QP_16		0x10
#define H264_INTRA_QP_16		0x10
#define H264_INTER_QP_40		0x28
#define H264_INTRA_QP_38		0x26
#define H264_BASELINE_PROFILE		0x42
#define H264_LEVEL_31			0x1F
#define H264_ENC_CAPBILITY		0x21

#define H264_RATE_CONTROL_MODE ((1<<(RATE_CONTROL_VBR_MODE-1)) \
	|(1<<(RATE_CONTROL_CONSTANT_QP_MODE-1)))

/* A.5. Video Class-Specific VC Interface Descriptor Subtypes */
#define UVC_VC_ENCODING_UNIT		0x07

enum {
	ENT_ID_STREAMING_INTERFACE,
	ENT_ID_CAMERA_TERMINAL,
	ENT_ID_PROCESSING_UNIT,
	ENT_ID_ENCODING_UNIT,
	ENT_ID_DEFAULT_EXTENSION_UNIT,
	ENT_ID_CUSTOM_EXTENSION_UNIT,
	ENT_ID_MS_EXTENSION_UNIT,
	ENT_ID_LAST_EXTENSION_UNIT = ENT_ID_MS_EXTENSION_UNIT,
	ENT_ID_OUTPUT_TERMINAL
};

#ifdef CONFIG_USB_RTSX_UVC_15
#define SRC_ID_EXTENSION_UNIT		ENT_ID_ENCODING_UNIT
#else
#define SRC_ID_EXTENSION_UNIT		ENT_ID_PROCESSING_UNIT
#endif

#define PU_CONTROL_UNDEFINED 0x00
#define PU_BACKLIGHT_COMPENSATION_CONTROL 0x01
#define PU_BRIGHTNESS_CONTROL 0x02
#define PU_CONTRAST_CONTROL 0x03
#define PU_GAIN_CONTROL 0x04
#define PU_POWER_LINE_FREQUENCY_CONTROL 0x05
#define PU_HUE_CONTROL 0x06
#define PU_SATURATION_CONTROL 0x07
#define PU_SHARPNESS_CONTROL 0x08
#define PU_GAMMA_CONTROL 0x09
#define PU_WHITE_BALANCE_TEMPERATURE_CONTROL 0x0A
#define PU_WHITE_BALANCE_TEMPERATURE_AUTO_CONTROL 0x0B
#define PU_WHITE_BALANCE_COMPONENT_CONTROL 0x0C
#define PU_WHITE_BALANCE_COMPONENT_AUTO_CONTROL 0x0D
#define PU_DIGITAL_MULTIPLIER_CONTROL 0x0E
#define PU_DIGITAL_MULTIPLIER_LIMIT_CONTROL 0x0F
#define PU_HUE_AUTO_CONTROL 0x10
#define PU_ANALOG_VIDEO_STANDARD_CONTROL 0x11
#define PU_ANALOG_LOCK_STATUS_CONTROL 0x12

#define CT_CONTROL_UNDEFINED 0x00
#define CT_SCANNING_MODE_CONTROL 0x01
#define CT_AE_MODE_CONTROL 0x02
#define CT_AE_PRIORITY_CONTROL 0x03
#define CT_EXPOSURE_TIME_ABSOLUTE_CONTROL 0x04
#define CT_EXPOSURE_TIME_RELATIVE_CONTROL 0x05
#define CT_FOCUS_ABSOLUTE_CONTROL 0x06
#define CT_FOCUS_RELATIVE_CONTROL 0x07
#define CT_FOCUS_AUTO_CONTROL 0x08
#define CT_IRIS_ABSOLUTE_CONTROL 0x09
#define CT_IRIS_RELATIVE_CONTROL 0x0A
#define CT_ZOOM_ABSOLUTE_CONTROL 0x0B
#define CT_ZOOM_RELATIVE_CONTROL 0x0C
#define CT_PANTILT_ABSOLUTE_CONTROL 0x0D
#define CT_PANTILT_RELATIVE_CONTROL 0x0E
#define CT_ROLL_ABSOLUTE_CONTROL 0x0F
#define CT_ROLL_RELATIVE_CONTROL 0x10
#define CT_PRIVACY_CONTROL 0x11
#define CT_ROI_CONTROL		0x14

#define SENSOR_FPS_120	120
#define SENSOR_FPS_60   60
#define SENSOR_FPS_40   40
#define SENSOR_FPS_30   30
#define SENSOR_FPS_25   25
#define SENSOR_FPS_24   24
#define SENSOR_FPS_23   23
#define SENSOR_FPS_20   20
#define SENSOR_FPS_15   15
#define SENSOR_FPS_12   12
#define SENSOR_FPS_11   11
#define SENSOR_FPS_10   10
#define SENSOR_FPS_9	9
#define SENSOR_FPS_8	8
#define SENSOR_FPS_7	7
#define SENSOR_FPS_5	5
#define SENSOR_FPS_3	3

#define CTL_MIN_CT_WHITBALANCETEMPAUTO (0)
#define CTL_MAX_CT_WHITBALANCETEMPAUTO (1)

#define CTL_MIN_CT_EXPOSURE_TIME_ABSOLUTE (50)
#define CTL_MAX_CT_EXPOSURE_TIME_ABSOLUTE (10000)

#define CTL_MIN_PU_PAN (-16)
#define CTL_MAX_PU_PAN (16)

#define CTL_MIN_PU_TILT (-12)
#define CTL_MAX_PU_TILT (12)

#define	REQUEST_TYPE		0x60
#define	STANDARD_REQUEST	0x00
#define	CLASS_REQUEST		0x20
#define	VENDOR_REQUEST		0x40

#define RC_UNDEFINED 0x00
#define SET_CUR 0x01
#define GET_CUR 0x81
#define GET_MIN 0x82
#define GET_MAX 0x83
#define GET_RES 0x84
#define GET_LEN 0x85
#define GET_INFO 0x86
#define GET_DEF 0x87

#define IF_IDX_VIDEOCONTROL 0x00
#define IF_IDX_VIDEOSTREAMING 0X01

#define VS_ERR_NOERROR (0)
#define VS_ERR_CNTPROTECT (1)
#define VS_ERR_IBUFUNDERRUN (2)
#define VS_ERR_DATDISCONT (3)
#define VS_ERR_OBUFUNDERRUN (4)
#define VS_ERR_OBUFOVERRUN (5)
#define VS_ERR_FMTCHANGE (6)
#define VS_ERR_STLIMGCAPERR (7)
#define VS_ERR_UNKNOWN (8)

#define DEV_CLOCK_FRQ 1000000

#define VC_CONTROL_UNDEFINED 0x00
#define VC_VIDEO_POWER_MODE_CONTROL 0x01
#define VC_REQUEST_ERROR_CODE_CONTROL 0x02

#define VC_ERR_NOERROR 0x00
#define VC_ERR_NOTRDY 0x01
#define VC_ERR_WRNGSTAT 0x02
#define VC_ERR_PWR 0x03
#define VC_ERR_OUTOFRANGE 0x04
#define VC_ERR_INVDUNIT 0x05
#define VC_ERR_INVDCTL 0x06
#define VC_ERR_INVDREQ 0x07
#define VC_ERR_UNKNOWN 0xFF

#define CT_EXPOSURE_TIME_ABSOLUTE_CONTROL 0x04
#define CT_PANTILT_ABSOLUTE_CONTROL 0x0D
#define PU_WHITE_BALANCE_TEMPERATURE_AUTO_CONTROL 0x0B

#define SCMD_DATA_VLD	0x80
#define SCMD_DIR_MSK	0x40
#define SCMD_DIR_IN	0x40
#define SCMD_DIR_OUT	0x00

#define VCMD_DBG	0x00
#define EXU1_CMD_STS	0x0A

#define VSCMD_IMEM_R			(0x01|SCMD_DATA_VLD|SCMD_DIR_IN)
#define VSCMD_XMEM_W			(0x02|SCMD_DATA_VLD|SCMD_DIR_OUT)
#define VSCMD_XMEM_R			(0x02|SCMD_DATA_VLD|SCMD_DIR_IN)
#define VSCMD_CODE_R			(0x03|SCMD_DATA_VLD|SCMD_DIR_IN)
#define VSCMD_BAR_INFO_READ		(0x20|SCMD_DATA_VLD|SCMD_DIR_IN)
#define VSCMD_DEV_STS_R			(0x0d|SCMD_DATA_VLD|SCMD_DIR_IN)
#define VSCMD_DEV_QUALIFICATION_GET	(0x10|SCMD_DATA_VLD|SCMD_DIR_IN)
#define VSCMD_IR_MODE_GET		(0x3A|SCMD_DATA_VLD|SCMD_DIR_IN)

#define ANDROIDUVC_IOC_MAGIC	0x74
#define ANDROIDUVC_SETFORMAT	1
#define ANDROIDUVC_CLEARFORMAT	2
#define ANDROIDUVC_QUERYFORMAT	3
#define ANDROIDUVC_WAIT_STREAM	4
#define ANDROIDUVC_STREAM_INTF	5
#define ANDROIDUVC_PRODUCE_DESC 6
#define ANDROIDUVC_CTL_INTF	7
#define ANDROIDUVC_RESET_EP	8
#define ANDROIDUVC_GET_METADATA_SUPPORT	9
#define ANDROIDUVC_STILL_IMAGE          (0x0A)
#define ANDROIDUVC_STILL_IMAGE_CLEAR	(0x0B)
#define ANDROIDUVC_SEND_METADATAR	(0x0C)
#define ANDROIDUVC_ALLOC_BUF		(0x0D)
#define ANDROIDUVC_FREE_BUF		(0x0E)

#define ANDROIDUVC_IOC_SETFORMAT	_IOW(ANDROIDUVC_IOC_MAGIC, \
	ANDROIDUVC_SETFORMAT, struct format_setting)
#define ANDROIDUVC_IOC_QUERYFORMAT	_IOWR(ANDROIDUVC_IOC_MAGIC, \
	ANDROIDUVC_QUERYFORMAT, struct format_setting)
#define ANDROIDUVC_IOC_CLRFORMAT	_IO(ANDROIDUVC_IOC_MAGIC, \
	ANDROIDUVC_CLEARFORMAT)
#define ANDROIDUVC_IOC_WAIT_STREAM	_IOWR(ANDROIDUVC_IOC_MAGIC, \
	ANDROIDUVC_WAIT_STREAM, int)
#define ANDROIDUVC_IOC_STREAM_INTF	_IOWR(ANDROIDUVC_IOC_MAGIC, \
	ANDROIDUVC_STREAM_INTF, int)
#define ANDROIDUVC_IOC_PRODUCE_DESC _IOWR(ANDROIDUVC_IOC_MAGIC, \
	ANDROIDUVC_PRODUCE_DESC, int)
#define ANDROIDUVC_IOC_CTL_INTF		_IOWR(ANDROIDUVC_IOC_MAGIC, \
	ANDROIDUVC_CTL_INTF, int)
#define ANDROIDUVC_IOC_BYPASS_PULLUP	_IO(ANDROIDUVC_IOC_MAGIC, \
	ANDROIDUVC_BYPASS_PULLUP)
#define ANDROIDUVC_IOC_WAIT_CLEARFEATURE _IOWR(ANDROIDUVC_IOC_MAGIC, \
	ANDROIDUVC_WAIT_CLEARFEATURE, int)
#define ANDROIDUVC_IOC_RESET_EP _IOWR(ANDROIDUVC_IOC_MAGIC, \
	ANDROIDUVC_RESET_EP, int)
#define ANDROIDUVC_IOC_GET_METADATA_SUPPORT _IOWR(ANDROIDUVC_IOC_MAGIC, \
	ANDROIDUVC_GET_METADATA_SUPPORT, int)
#define ANDROIDUVC_IOC_STILL_IMAGE _IOWR(ANDROIDUVC_IOC_MAGIC, \
	ANDROIDUVC_STILL_IMAGE, int)
#define ANDROIDUVC_IOC_STILL_IMAGE_CLEAR _IOWR(ANDROIDUVC_IOC_MAGIC, \
	ANDROIDUVC_STILL_IMAGE_CLEAR, int)
#define ANDROIDUVC_IOC_SEND_METADATA  _IOWR(ANDROIDUVC_IOC_MAGIC, \
	ANDROIDUVC_SEND_METADATAR, struct metadata_buffer)
#define ANDROIDUVC_IOC_ALLOC_BUF _IOWR(ANDROIDUVC_IOC_MAGIC, \
	ANDROIDUVC_ALLOC_BUF, struct uvc_dma_buf)
#define ANDROIDUVC_IOC_FREE_BUF _IOWR(ANDROIDUVC_IOC_MAGIC, \
	ANDROIDUVC_FREE_BUF, struct uvc_dma_buf)

#define RLX_TRACE_ERROR		(1 << 0)
#define RLX_TRACE_PROBE		(1 << 1)
#define RLX_TRACE_CONTROL	(1 << 2)
#define RLX_TRACE_IOCTL		(1 << 3)
#define RLX_TRACE_BUF		(1 << 4)
#define RLX_TRACE_VIDEO		(1 << 5)
#define RLX_TRACE_STATUS	(1 << 6)
#define RLX_TRACE_DEBUG		(1 << 7)
#define RLX_TRACE_INFO		(1 << 8)
#define RLX_TRACE_NOTICE	(1 << 9)
#define RLX_TRACE_WARNING	(1 << 10)
#define RLX_TRACE_REG		(1 << 11)

#define RLX_TRACE_DEFAULT	RLX_TRACE_ERROR

extern int rlx_uvc_debug;

#define rlxprintk(flag, arg...) \
	do { \
		if (rlx_uvc_debug & flag) \
			printk(KERN_DEBUG "rlx_uvc:"arg);\
	} while (0)

int uvc_bind_config(struct usb_configuration *c,
		    const struct uvc_descriptor_header *const *fs_control,
		    const struct uvc_descriptor_header *const *hs_control,
		    const struct uvc_descriptor_header *const *fs_streaming,
		    const struct uvc_descriptor_header *const *hs_streaming,
		    const struct uvc_descriptor_header *const *ss_streaming);

void uvc_function_setup_continue(struct uvc_device *uvc);

void uvc_function_connect(struct uvc_device *uvc);

void uvc_function_disconnect(struct uvc_device *uvc);

int uvc_outdata_setstall(void);

#endif /* _F_UVC_H_ */
