/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (c) 2025 Realtek Semiconductor Corp. All rights reserved.
 *
 * THIS SOFTWARE IS CONFIDENTIAL AND PROPRIETARY TO REALTEK SEMICONDUCTOR
 * CORP. DISCLOSURE, REPRODUCTION, REDISTRIBUTION, IN WHOLE OR IN PART, OF
 * THIS WORK AND ITS DERIVATIVES WITHOUT EXPRESS PERMISSION IS PROHIBITED.
 *
 * REALTEK SEMICONDUCTOR CORP. RESERVES THE RIGHT TO UPDATE, MODIFY, OR
 * DISCONTINUE THIS SOFTWARE AT ANY TIME WITHOUT NOTICE. THIS SOFTWARE IS
 * PROVIDED BY THE REGENTS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE REGENTS AND CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

#ifndef _U_RTS_BWT_MONITOR_H
#define _U_RTS_BWT_MONITOR_H

#include <linux/types.h>
#include <linux/ioctl.h>

#define RTSBWT_MAX_PACKET_TYPE          4

struct rtsbwt_cfg {
	__u8 write;
	__u32 start_addr;
	__u32 end_addr;
	__u32 jump_addr;
	__u8 packet_num[RTSBWT_MAX_PACKET_TYPE];
	__u16 trans_num;
};

struct rtsbwt_counter {
	__u8 write;
	__u32 cycle;
	__u32 data;
	__u32 transfer;
};

#define RTSBWT_IOC_MAGIC		'b'

#define RTSBWT_IOC_GET_COUNTER		_IOWR(RTSBWT_IOC_MAGIC, 1,\
					struct rtsbwt_counter)
#define RTSBWT_IOC_SET_CFG		_IOWR(RTSBWT_IOC_MAGIC, 2,\
					struct rtsbwt_cfg)
#define RTSBWT_IOC_STOP_WRITE		_IOW(RTSBWT_IOC_MAGIC, 3, __u8)
#define RTSBWT_IOC_STOP_READ		_IOW(RTSBWT_IOC_MAGIC, 4, __u8)
#define RTSBWT_IOC_START		_IOW(RTSBWT_IOC_MAGIC, 5, __u8)
#define RTSBWT_IOC_WAIT_WRITE_DONE	_IOW(RTSBWT_IOC_MAGIC, 6, unsigned long)
#define RTSBWT_IOC_WAIT_READ_DONE	_IOW(RTSBWT_IOC_MAGIC, 7, unsigned long)
#define RTSBWT_IOC_WAIT_INTERRUPT	_IOW(RTSBWT_IOC_MAGIC, 8, unsigned long)
#define RTSBWT_IOC_DRAM_CLK_RATE	_IOWR(RTSBWT_IOC_MAGIC, 9, unsigned long)
#define RTSBWT_IOC_MAXNR		9

#endif
