/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (c) 2025 Realtek Semiconductor Corp. All rights reserved.
 *
 * THIS SOFTWARE IS CONFIDENTIAL AND PROPRIETARY TO REALTEK SEMICONDUCTOR
 * CORP. DISCLOSURE, REPRODUCTION, REDISTRIBUTION, IN WHOLE OR IN PART, OF
 * THIS WORK AND ITS DERIVATIVES WITHOUT EXPRESS PERMISSION IS PROHIBITED.
 *
 * REALTEK SEMICONDUCTOR CORP. RESERVES THE RIGHT TO UPDATE, MODIFY, OR
 * DISCONTINUE THIS SOFTWARE AT ANY TIME WITHOUT NOTICE. THIS SOFTWARE IS
 * PROVIDED BY THE REGENTS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE REGENTS AND CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

#ifndef _LINUX_RTS_CAMERA_H
#define _LINUX_RTS_CAMERA_H

#include <linux/ioctl.h>
#include <linux/types.h>

#define RTSCAM_MAX_PLANES_NUM 2

#define RTSCAM_DEV_MAJOR		82

#define RTS_V4L2_CID_BASE		(V4L2_CID_USER_BASE | 0xf000)
#define RTS_V4L2_CID_ROLL_ABSOLUTE	(RTS_V4L2_CID_BASE + 0)
#define RTS_V4L2_CID_AUTO_WHITE_BALANCE_COMPONENT	(RTS_V4L2_CID_BASE + 1)
#define RTS_V4L2_CID_GREEN_BALANCE	(RTS_V4L2_CID_BASE + 2)
#define RTS_V4L2_CID_Y_GAIN		(RTS_V4L2_CID_BASE + 3)
#define RTS_V4L2_CID_SNR_CROP_X		(RTS_V4L2_CID_BASE + 4)
#define RTS_V4L2_CID_SNR_CROP_Y		(RTS_V4L2_CID_BASE + 5)
#define RTS_V4L2_CID_DAYNIGHT_STATIS    (RTS_V4L2_CID_BASE + 26)

#define RTS_V4L2_CID_GRAY_MODE          (RTS_V4L2_CID_BASE + 6)
#define RTS_V4L2_CID_WDR_MODE           (RTS_V4L2_CID_BASE + 7)
#define RTS_V4L2_CID_WDR_LEVEL          (RTS_V4L2_CID_BASE + 8)
#define RTS_V4L2_CID_3DNR               (RTS_V4L2_CID_BASE + 9)
#define RTS_V4L2_CID_DEHAZE             (RTS_V4L2_CID_BASE + 10)
#define RTS_V4L2_CID_IR_MODE            (RTS_V4L2_CID_BASE + 11)
#define RTS_V4L2_CID_SMART_IR_MODE      (RTS_V4L2_CID_BASE + 12)
#define RTS_V4L2_CID_SMART_IR_MANUAL_LEVEL      (RTS_V4L2_CID_BASE + 13)
#define RTS_V4L2_CID_IN_OUT_DOOR_MODE   (RTS_V4L2_CID_BASE + 14)
#define RTS_V4L2_CID_NOISE_REDUCTION    (RTS_V4L2_CID_BASE + 15)
#define RTS_V4L2_CID_DETAIL_ENHANCEMENT (RTS_V4L2_CID_BASE + 16)
#define RTS_V4L2_CID_LDC                (RTS_V4L2_CID_BASE + 17)
#define RTS_V4L2_CID_DYNAMIC_FPS        (RTS_V4L2_CID_BASE + 18)
#define RTS_V4L2_CID_FOV_MODE           (RTS_V4L2_CID_BASE + 19)
#define RTS_V4L2_CID_CCM_AUTO           (RTS_V4L2_CID_BASE + 20)
#define RTS_V4L2_CID_CCM_MATRIX         (RTS_V4L2_CID_BASE + 21)
#define RTS_V4L2_CID_Y_GAMMA_AUTO       (RTS_V4L2_CID_BASE + 22)
#define RTS_V4L2_CID_Y_GAMMA_CURVE      (RTS_V4L2_CID_BASE + 23)
#define RTS_V4L2_CID_RGB_GAMMA_AUTO     (RTS_V4L2_CID_BASE + 24)
#define RTS_V4L2_CID_RGB_GAMMA_CURVE    (RTS_V4L2_CID_BASE + 25)
#define RTS_V4L2_CID_DAYNIGHT_STATIS	(RTS_V4L2_CID_BASE + 26)

struct rtscam_vcmd {
	unsigned int cmdcode;
	void *arg;
};

struct rtscam_addr {
	unsigned long addr;
	int index;
};

enum {
	RTS_VIN_MODE_NO_MEM,
	RTS_VIN_MODE_RING_MEM,
	RTS_VIN_MODE_NORMAL
};

#define RTSCAMIOC_VENDOR_CMD		_IOWR('r', 0x01, struct rtscam_vcmd)
#define RTSCAMIOC_GET_PHYADDDR		_IOWR('r', 0x02, struct rtscam_addr)
#define RTS_VIDIOC_SET_FOV_MODE		_IOW('r', 0x03, int)
#define RTS_VIDIOC_GET_FOV_MODE		_IOR('r', 0x04, int)

#define VIDIOC_SET_VIN_MODE		_IOW('V', 104, int)
#endif
