/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (c) 2025 Realtek Semiconductor Corp. All rights reserved.
 *
 * THIS SOFTWARE IS CONFIDENTIAL AND PROPRIETARY TO REALTEK SEMICONDUCTOR
 * CORP. DISCLOSURE, REPRODUCTION, REDISTRIBUTION, IN WHOLE OR IN PART, OF
 * THIS WORK AND ITS DERIVATIVES WITHOUT EXPRESS PERMISSION IS PROHIBITED.
 *
 * REALTEK SEMICONDUCTOR CORP. RESERVES THE RIGHT TO UPDATE, MODIFY, OR
 * DISCONTINUE THIS SOFTWARE AT ANY TIME WITHOUT NOTICE. THIS SOFTWARE IS
 * PROVIDED BY THE REGENTS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE REGENTS AND CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

#ifndef _U_RTS_CAMERA_OSD_H
#define _U_RTS_CAMERA_OSD_H

#define RTSOSD2_IOC_MAGIC	'o'

#define RTSOSD2_IOCGHWOFFSET \
			_IOR(RTSOSD2_IOC_MAGIC, 1, unsigned long *)
#define RTSOSD2_IOCGHWIOSIZE \
			_IOR(RTSOSD2_IOC_MAGIC, 2, unsigned int *)
#define RTSOSD2_IOCDONE		_IO(RTSOSD2_IOC_MAGIC, 3)
#define RTSOSD2_IOC_ENABLE	_IO(RTSOSD2_IOC_MAGIC, 4)
#define RTSOSD2_IOC_DISABLE	_IO(RTSOSD2_IOC_MAGIC, 5)
#define RTSOSD2_IOC_WAIT_INTERRUPT	_IO(RTSOSD2_IOC_MAGIC, 6)

#define RTSOSD2_IOC_MAXNR	6

#endif
