/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (c) 2025 Realtek Semiconductor Corp. All rights reserved.
 *
 * THIS SOFTWARE IS CONFIDENTIAL AND PROPRIETARY TO REALTEK SEMICONDUCTOR
 * CORP. DISCLOSURE, REPRODUCTION, REDISTRIBUTION, IN WHOLE OR IN PART, OF
 * THIS WORK AND ITS DERIVATIVES WITHOUT EXPRESS PERMISSION IS PROHIBITED.
 *
 * REALTEK SEMICONDUCTOR CORP. RESERVES THE RIGHT TO UPDATE, MODIFY, OR
 * DISCONTINUE THIS SOFTWARE AT ANY TIME WITHOUT NOTICE. THIS SOFTWARE IS
 * PROVIDED BY THE REGENTS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE REGENTS AND CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

#ifndef _LINUX_RTS_CAMERA_LOCK_H
#define _LINUX_RTS_CAMERA_LOCK_H

#define RTSCAMLOCK_IOC_MAGIC	'l'

struct rtscam_lock_num {
	unsigned long key;
	int num;
};

struct rtscam_lock_name {
	unsigned long key;
	char name[16];
};

#define RTSCAMLOCK_IOC_ALLOC	_IOW(RTSCAMLOCK_IOC_MAGIC, 0x1, unsigned long)
#define RTSCAMLOCK_IOC_FREE	_IOW(RTSCAMLOCK_IOC_MAGIC, 0x2, unsigned long)
#define RTSCAMLOCK_IOC_INIT	\
	_IOW(RTSCAMLOCK_IOC_MAGIC, 0x3, struct rtscam_lock_num)

#define RTSCAMLOCK_IOC_WAIT	_IOW(RTSCAMLOCK_IOC_MAGIC, 0x4, unsigned long)
#define RTSCAMLOCK_IOC_POST	_IOW(RTSCAMLOCK_IOC_MAGIC, 0x5, unsigned long)
#define RTSCAMLOCK_IOC_SET_NAME	\
	_IOW(RTSCAMLOCK_IOC_MAGIC, 0x6, struct rtscam_lock_name)

#endif
