/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (c) 2025 Realtek Semiconductor Corp. All rights reserved.
 *
 * THIS SOFTWARE IS CONFIDENTIAL AND PROPRIETARY TO REALTEK SEMICONDUCTOR
 * CORP. DISCLOSURE, REPRODUCTION, REDISTRIBUTION, IN WHOLE OR IN PART, OF
 * THIS WORK AND ITS DERIVATIVES WITHOUT EXPRESS PERMISSION IS PROHIBITED.
 *
 * REALTEK SEMICONDUCTOR CORP. RESERVES THE RIGHT TO UPDATE, MODIFY, OR
 * DISCONTINUE THIS SOFTWARE AT ANY TIME WITHOUT NOTICE. THIS SOFTWARE IS
 * PROVIDED BY THE REGENTS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE REGENTS AND CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

#ifndef _U_RTS_CAMERA_ISP_H
#define _U_RTS_CAMERA_ISP_H

#include <linux/ioctl.h>
#include "rts_camera_isp_snr.h"
#include "rts_camera_isp_info.h"

struct rtscam_isp_mem_alloc_info {
	__u32 phy_addr;
	__u32 length;
	char info[32];
};

enum rtscam_isp_pin_state {
	PIN_STATE_NONE,
	PIN_STATE_DVP,
	PIN_STATE_MIPI,
};

enum rtscam_isp_clock_type {
	CLOCK_INTERFACE,
	CLOCK_ISP,
	CLOCK_MIPIOUT,
};

struct rtscam_isp_clock {
	enum rtscam_isp_clock_type type;
	unsigned long rate;
};

struct rts_isp_mem_sync_info {
	unsigned long addr;
	unsigned long size;
	int sync_type;
	int dma_dir;
};

enum rtscam_isp_event {
	RTSCAM_ISP_DATA_START,
	RTSCAM_ISP_FRAME_END,
};

#define RTSISP_IOC_MAGIC 'E'

#define RTSISP_IOC_GET_IO_START _IOR(RTSISP_IOC_MAGIC, 0, __u32)
#define RTSISP_IOC_GET_IO_SIZE _IOR(RTSISP_IOC_MAGIC, 1, __u32)
#define RTSISP_IOC_POWER _IOW(RTSISP_IOC_MAGIC, 2, struct rts_isp_snr_pwr)
#define RTSISP_IOC_I2C_READ_REGS _IOWR(RTSISP_IOC_MAGIC, 3, struct rts_isp_i2c)
#define RTSISP_IOC_I2C_WRITE_REGS _IOW(RTSISP_IOC_MAGIC, 4, struct rts_isp_i2c)
#define RTSISP_IOC_SET_INFO _IOW(RTSISP_IOC_MAGIC, 5, struct rts_isp_info)
#define RTSISP_IOC_SYNC_WRITE _IOW(RTSISP_IOC_MAGIC, 7, \
				   struct rts_isp_sync_regs)
#define RTSISP_IOC_INIT_STATIS _IOW(RTSISP_IOC_MAGIC, 8, __u32)
#define RTSISP_IOC_CLEANUP_STATIS _IO(RTSISP_IOC_MAGIC, 9)
#define RTSISP_IOC_GET_STATIS_INFO _IOR(RTSISP_IOC_MAGIC, 10, \
					struct rts_isp_statis_info)
#define RTSISP_IOC_PUT_STATIS _IOW(RTSISP_IOC_MAGIC, 11, __u32)
#define RTSISP_IOC_MEM_ALLOC _IOWR(RTSISP_IOC_MAGIC, 12, \
				   struct rtscam_isp_mem_alloc_info)
#define RTSISP_IOC_MEM_FREE _IOW(RTSISP_IOC_MAGIC, 13, __u32)
#define RTSISP_IOC_SEL_PIN_STATE _IOW(RTSISP_IOC_MAGIC, 14, \
				      enum rtscam_isp_pin_state)
#define RTSISP_IOC_NOTIFY_DYN_FPS _IOW(RTSISP_IOC_MAGIC, 15, struct v4l2_fract)
#define RTSISP_IOC_GET_ISP_CLOCK _IO(RTSISP_IOC_MAGIC, 16)
#define RTSISP_IOC_PUT_ISP_CLOCK _IO(RTSISP_IOC_MAGIC, 17)
#define RTSISP_IOC_SET_CLOCK _IOWR(RTSISP_IOC_MAGIC, 18, \
				   struct rtscam_isp_clock)
#define RTSISP_IOC_IS_FPGA _IOR(RTSISP_IOC_MAGIC, 19, __s32)
#define RTSISP_IOC_WAIT_EVENT _IOW(RTSISP_IOC_MAGIC, 20, __s32)
#define RTSISP_IOC_SYNC_LOCK _IOW(RTSISP_IOC_MAGIC, 21, __s32)
#define RTSISP_IOC_TEST_PREVIEW _IOW(RTSISP_IOC_MAGIC, 22, struct v4l2_fract)
#define RTSISP_IOC_GET_TNR_BIT _IOR(RTSISP_IOC_MAGIC, 23, __u32)
#define RTSISP_IOC_MEM_SYNC _IOW(RTSISP_IOC_MAGIC, 24, \
				 struct rts_isp_mem_sync_info)
#define RTSISP_IOC_I2C_TRANSTER _IOWR(RTSISP_IOC_MAGIC, 25, struct i2c_msg)
#define RTSISP_IOC_NOTIFY_COLOR_RANGE _IOW(RTSISP_IOC_MAGIC, 26, __s32)
#define RTSISP_IOC_GET_TIMEOUT _IOR(RTSISP_IOC_MAGIC, 27, __s32)

#endif /* _U_RTS_CAMERA_ISP_H */
