#ifndef __IPC_TTF_H__
#define __IPC_TTF_H__

#ifdef __cplusplus
extern "C" {
#endif

#include <ipc_core.h>

typedef struct {
    vptr data;
    s32 width;
    s32 height;
} ipc_rgba_t, *ipc_rgba_p;

/**
 * @brief Initializes TTF loading (Note: currently loads the entire TTF into memory, which may cause OOM).
 *
 * @param ttf_path Path to the TTF font file.
 * @return NULL: File cannot be opened or insufficient memory. Otherwise, returns a valid handle.
 */
vptr ipc_ttf_init(pv8 ttf_path);

/**
 * @brief Releases resources loaded by ipc_ttf_init.
 *
 * @param handle Handle returned by ipc_ttf_init.
 */
void ipc_ttf_uninit(vptr handle);

/**
 * @brief Generates an RGBA image based on the input Unicode.
 *
 * @param handle Handle returned by ipc_ttf_init.
 * @param unicode Array of Unicode characters to generate the image for.
 * @param size Length of the Unicode array.
 * @param pixels Font size (height in pixels).
 * @param rgba Pointer to store the generated RGBA image information.
 * @return
 *  IPC_INVALID_ARGS: Invalid arguments.
 *  IPC_NOT_NEED: Input Unicode characters are all invisible symbols, no need to generate RGBA.
 *  IPC_NOMEM: Memory allocation failed.
 *  IPC_SUCCESS: Success.
 * @note Supports '\n' for line breaks.
 * @note The generated RGBA must be destroyed by calling ipc_ttf_del_rgba.
 */
s32 ipc_ttf_new_rgba(vptr handle, pu32 unicode, s32 size, u32 pixels, ipc_rgba_p rgba);

/**
 * @brief Destroys the RGBA image generated by ipc_ttf_new_rgba.
 *
 * @param rgba RGBA image information generated successfully from ipc_ttf_new_rgba.
 */
void ipc_ttf_del_rgba(ipc_rgba_p rgba);

#ifdef __cplusplus
}
#endif

#endif //__IPC_TTF_H__